### ISSUE TITLE
Determine if MSYS, Cygwin, and WSL can be used interchangeabley

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#13] opened 2017-12-05 00:16 UTC
MSYS, Cygwin, and Windows Subsystem for Linux (WSL) are three options for compiling Makefiles on Windows.  Each of these has bash.exe, but unfortunately each seems to operate slightly differently.  

For example, when using Cygwin, a command might look like this:
`self.run("bash -c ^'configure^'")`

While on MSYS, the same command must be run like this: 
`self.run("bash -c '{config_cmd}'")`

I do not know what the equivalent is for WSL.  

Currently, there are several tools for working with Cygwin and MSYS. 
http://conanio.readthedocs.io/en/latest/reference/tools.html#tools-run-in-windows-bash
 
The goal is for someone who has time and experience with all three tools to determine and summarize any known challenges with writing a recipe in such a way that any of the three environments would suffice (so long as bash.exe is on the path).

**Comment by dimi309** [comment] 2017-12-05 02:32
When looking into this, it may be worth keeping this issue in mind https://github.com/conan-io/conan/issues/1281, re-ascertaining it has been resolved, and making sure we understand its implications.

**Comment by solvingj** [comment] 2017-12-05 03:26
Great history,  thanks for posting!  I think there’s another from me and/or sigmoidal somewhere.

**Comment by dimi309** [comment] 2017-12-05 06:53
Thanks @solvingj ! Note that the thread ended up touching on various issues, some resolved and some not. Some of the posts refer to mingw, others to cygwin. Personally, I sort of quit on automake with mingw, now only building packages on mingw when libraries support cmake, for the reason mentioned in this comment https://github.com/conan-io/conan/issues/1281#issuecomment-305391681 but it would be great if we could figure out the best way to complete such a build.

**Comment by sztomi** [comment] 2017-12-05 09:38
I'd argue against stitching strings together. Instead, we should write a temporary script file and pass  it as a param to bash. At $work we have a context manager that monkey patches `self` to do that:

```py
    with cygwin(self):
        self.run("...") # will be written to a file and executed via cygwin bash
```

**Comment by sztomi** [comment] 2017-12-05 21:29
Another thought: if mingw/cygwin/wsl is used for building something, they are most certainly not interchangable. The WSL is real linux running on top of syscalls implemented in windows. You run ELF executables and usually produce them as well (unless you cross-compile). cygwin vs mingw might produce binaries that are accidentally binary compatible but I wouldn't count on that.

**Comment by dimi309** [comment] 2017-12-06 04:52
And just to be clear @sztomi, I suppose that this is a problem because the signature of a binary package created with say, cygwin, would be exactly the same as the one for a mingw binary? That would mean that a machine that runs both could get the binaries mixed up, no? With one overwriting the other?

**Comment by sztomi** [comment] 2017-12-06 09:48
@dimi309 the signature is computed from the settings and options of the package, not the actual file output (which would be brittle). Conan also does not have a cygwin-gcc, mingw-gcc and wsl-gcc compiler in the default settings.yml. The question if *we* treat them interchangeably e.g.

```py
if self.settings.os == "Windows" and self.settings.compiler == "gcc":
    # can we mix and match cygwin/mingw/wsl here between different packages?
```

and my answer is a strong no.

**Comment by solvingj** [comment] 2017-12-06 10:29
It’s possible interchangeable was the wrong word. Instead, can we write a build method with a single syntax, which can be translated to be built by any of the three.  The goal is to avoid writing three separate methods in every recipe, and the logic to choose between the three. 

If msys 
elif cygwin 
elif wsl 

The idea is that if we write three such methods in several recipes over and over, and they are different mostly by escape characters, then maybe we can write a unified helper.  Maybe not though.  The note about binary compatibility is good. @SSE4 any thoughts?

**Comment by dimi309** [comment] 2017-12-06 10:30
@solvingj I think the problem is that if you have both cygwin and mingw on a machine they will start overwriting each other..

**Comment by dimi309** [comment] 2017-12-06 10:35
The other thing that worries me is this msys-configure vs mingw-makefiles incopatibility let's say, that has been blocking me from deploying autotools-based libraries for mingw. Does someone have an obvious way around it that I have been missing?

**Comment by dimi309** [comment] 2017-12-06 10:39
So far I have been treating mingw builds as a "very nice to have", doing my best to provide them, but only trying them locally and not standardising them on appveyor. Sometimes I just can't complete them. I hope that if we put our heads together we can resolve enough issues to be able to start routinely providing such builds. But I haven't managed to do it myself so far and it may be a bit challenging...

**Comment by dimi309** [comment] 2017-12-06 11:11
Btw I think it's related, since @sztomi and I were also having this discussion: https://github.com/bincrafters/community/issues/15 about a package, I think that there are many questions to resolve and many things that we can possibly learn from each other about how we all have been performing mingw, msys, cygwin, etc builds... Maybe we should try to put a sort of table or list together of what these matters are and try to come up with a common strategy? I could start it tonight if you think it's a good idea (as in, in quite a few hours...)

**Comment by solvingj** [comment] 2017-12-06 11:26
Yes, agreed, more and more it's looking like there is a general manageability problem with PATH, surrounding windows build tools which conflict, and we're trying to solve the problem at too low a level.  We are officially in the weeds.  

Note:  This is closely related to the following issue: https://github.com/conan-io/conan/issues/2096

To recap, Conan provides great capabilities for `build_requires` to add themselves to PATH during an execution.  Ideally, the policy could be that everything can controlled by using `build_requires` rather than pre-installed versions of tools.  However, existing PATH entries will continue to conflict, and simply clearing the PATH at start is not always going to be an option, so something new is needed.  

So far, I am aware of about 7 tool installations involved in these types of conflicts: Visual Studio, MSYS, Cygwin, WSL, MinGW, Git for windows, Strawberry Perl. 

At this moment, a reliable and fully-automated mechanism for handling all conflicts seems very hard to imagine.

**Comment by dimi309** [comment] 2017-12-06 12:30
At the same time, may I propose that we do not allow this to bog us down? I think it is a sign of organisational maturity let's say (and I know that I'm overdoing it in more ways than one in expressing it as such) that we have decided to take a step back and have a look at expanding our capabilities to be more organised about mingw/cygwin/etc. as is also the case with the whole thinking about character casing we have had yesterday. But we may start running the risk of spending too much time and energy on things that are important indeed, but at the expense of things that bring a lot more value. I think that we already have a respectable collection of packages that mostly guarantee a build across Linux, MacOS and Windows, at least with Visual Studio and, often, with one of the gcc / llvm windows ports, and a mechanism that continues to produce more packages, with foreseeable specs and quality. I use the packaged libraries myself and I think they already do a great service to project setup, experimentation and cross-platform builds, so that part is already conquered territory and it should remain as such. In view of that, let's continue creating and publishing packages while we are thinking about the additional other factors. For example (and not because it was me submitting it) I think that conan-opus should be published (https://github.com/bincrafters/community/issues/15), because it's no worse than, say conan-vorbis or many other packages that can't be built with mingw. Until we sort out the gcc / llvm over windows issue, how about we continue to consider them a "nice to have" and keep packaging?

**Comment by SSE4** [comment] 2017-12-06 14:44
first off, I like @sztomi idea about cygwin/msys context helpers. that's definitely something we can look into.

for WSL, @sztomi is also right. WSL only capable to run Linux (ELF) binaries. although Makefile build technically may invoke any compiler specified by CC/CXX environment variable, WSL will be unable to execute regular MinGW (unless using Wine or installing native Linux MinGW for cross-compiling).

for Cygwin/MSYS - they are almost interchangeable. both Make from Cygwin and Make from MSYS may invoke either MinGW or Visual Studio. however, you probably can't just use the same recipe without many quirks. first off, Cygwin and MSYS are using different path flavors (**/c/bincrafters** VS **/cygdrive/c/bincrafters**). second, there are other portability issues - e.g. some Makefiles only know about Cygwin and not about MSYS (e.g. libiconv), and patching is necessary.

for bash - in general the same syntax `bash -l {command}` may be used everywhere - for WSL, MSYS, Cygwin, or whatever you have bash from.

**Comment by SSE4** [comment] 2017-12-07 06:10
#https://github.com/conan-io/conan/issues/2120

**Comment by dimi309** [comment] 2017-12-08 04:21
I've added a comment to the [above mentioned conversation](https://github.com/conan-io/conan/issues/2120#issuecomment-350166920) I may be wrong and I am more that willing to work with any result that comes our of our discussion, but I am wondering if we are trying to over-engineer something that can never be adequately perfected and if we should return to @solvingj 's original question and assume that these systems can be used interchangeably if we do a best effort to produce builds that run on as many of them as possible, assuming however that the user only uses one of them at a time.

**Comment by SSE4** [comment] 2018-01-21 07:52
closing as already decided

**Closed by SSE4** 2018-01-21 07:52 UTC
