### ISSUE TITLE
 abseil/20180223 - Wrong linkage order

### ISSUE THREAD

**Issue by r-darwish** [bincrafters/community#176] opened 2018-03-13 15:35 UTC
### Description of Problem, Request, or Question
Trying to build [this app](https://gist.github.com/r-darwish/3bb4b603a39fd551396a7c8f9d49f226) caused the following linkage command:
```shell
/usr/bin/c++ -std=c++11 -rdynamic CMakeFiles/atest.dir/main.cpp.o -o bin/atest -L/home/roeyd/.conan/data/abseil/20180223/bincrafters/stable/package/d2b9b1e5dc4f75ac827291c9bda9970b49137f53/lib -L/home/roeyd/.conan/data/cctz/2.2/bincrafters/stable/package/b60023f9fa06321277cb53d223d0048027c27904/lib -Wl,-rpath,/home/roeyd/.conan/data/abseil/20180223/bincrafters/stable/package/d2b9b1e5dc4f75ac827291c9bda9970b49137f53/lib:/home/roeyd/.conan/data/cctz/2.2/bincrafters/stable/package/b60023f9fa06321277cb53d223d0048027c27904/lib -labsl_algorithm -labsl_container -labsl_memory -labsl_dynamic_annotations -labsl_spinlock_wait -labsl_meta -labsl_utility -labsl_stack_consumption -labsl_throw_delegate -labsl_span -labsl_bad_optional_access -labsl_any -ltest_instance_tracker_lib -labsl_int128 -labsl_numeric -labsl_stacktrace -labsl_malloc_internal -labsl_base -labsl_leak_check -labsl_bad_any_cast -labsl_optional -labsl_malloc_extension -labsl_debugging -labsl_time -labsl_strings -labsl_synchronization -lpthread -lcctz 
```

Which caused the following error:

```shell
sysinfo.cc:(.text+0x452): undefined reference to `AbslInternalSpinLockWake'
```

This is due to the fact that `-labsl_spinlock_wait`, which contains `AbslInternalSpinLockWake`, comes before `-labsl_base`, which depends on it. As stated [here](https://stackoverflow.com/questions/11893996/why-does-the-order-of-l-option-in-gcc-matter), the order should be reversed. Running the same command when moving `-labsl_spinlock_wait` to end of the command seems to work.

The current implementation of `package_info` calls `tools.collect_libs`, which in turn calls `os.listdir`, which does not guarantee any order, so the problem reproduces randomly.

### Package Details (Include if Applicable)
* Package Name/Version: **abseil/20180223**
* Operating System: **Arch Linux**
* Compiler+version: **gcc-7.3**

### Steps to reproduce (Include if Applicable)
Compile the program above.

**Comment by solvingj** [comment] 2018-03-14 17:26
@r-darwish Are we able to fix the link order manually now that we know of the issue?

**Comment by bschindler** [comment] 2018-03-26 11:17
@solvingj I got notified of this issue as I ran into a similar issue. In my case, it was a package which attempted to install some system libraries and then link against them. But since the library was only added as if it was part of the package, conan did not know that there was a dependency between the two. As soon another package (or some other command) added a link dependency to the system library, cmake sometimes reordered the link order which made compilation break. 

So essentially, this is an issue for every package doing something like: 
``` 
installer.install("%s%s" % ("somelib", arch_suffix))
... 
self.cpp_info.libs = ['package_lib' 'somelib']
```
cmake (or any other build system) has no knowledge that package_lib depends on somelib which gives potential for link failures

**Comment by drrlvn** [comment] 2018-03-26 11:52
Unless I'm missing something, it looks like abseil's `CMakeLists.txt` correctly specifies that `absl_base` depends on `absl_spinlock_wait` [here](https://github.com/abseil/abseil-cpp/blob/master/absl/base/CMakeLists.txt#L83). If so then this bug should not happen regardless of the order returned by `tools.collect_libs`.

**Comment by drrlvn** [comment] 2018-05-02 12:00
The testing branch works for me, thanks!

**Comment by SSE4** [comment] 2018-05-02 12:06
confirmed as fixed, closing

**Closed by SSE4** 2018-05-02 12:06 UTC
Labels: bug, feedback

**Comment by SimonEbner** [comment] 2018-09-14 09:59
@bschindler sorry for hijacking the topic but I do have exactly this situation that you mention
```
installer.install("%s%s" % ("somelib", arch_suffix))
... 
self.cpp_info.libs = ['package_lib' 'somelib']
```
Is there any solution in conan how to handle this situation? In my specific case I am talking about openssl with libcryto that has a dependency on libdl.
