### ISSUE TITLE
Build SOIL2 MINGW

### ISSUE THREAD

**Issue by MHATN** [bincrafters/community#1196] opened 2020-05-14 16:23 UTC
Hello, 
while I'm trying to build soil2 for code::blocks I got this error:

"==== Building soil2-static-lib (debug) ===="
Linking soil2-static-lib
process_begin: CreateProcess(NULL, ar -rcs ../../lib/windows/libsoil2-debug.a ../../obj/windows/debug/soil2-static-lib/image_DXT.o ../../obj/windows/debug/soil2-static-lib/image_helper.o ../../obj/windows/debug/soil2-static-lib/SOIL2.o ../../obj/windows/debug/soil2-static-lib/wfETC.o, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [../../lib/windows/libsoil2-debug.a] Error 2
make: *** [soil2-static-lib] Error 2

I don't know what to do and I'm beginner, please help

**Comment by Lemiort** [comment] 2020-05-16 16:11
I think u just don't have library file because of 
https://github.com/bincrafters/community/issues/1188

**Comment by Croydon** [comment] 2020-07-07 23:02
Closing as a duplicate of #1188

**Closed by Croydon** 2020-07-07 23:02 UTC
Labels: question
