### ISSUE TITLE
Inclusion Request: quazip

### ISSUE THREAD

**Issue by alnkpa** [bincrafters/community#1143] opened 2020-03-03 12:17 UTC
### Package Details
  * Package Name: **quazip**
  * Operating Systems+versions: **Linux Ubuntu 18.04, Windows 10, macOS Mojave**
  * Compiler support: **gcc-9, clang9, MSVC 2019**
  * Conan recipe repository: **https://github.com/alnkpa/conan-quazip**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [ ] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter:
      * macOS build fails with
```
CMake Error in source_subfolder/quazip/CMakeLists.txt:

  No known features for CXX compiler


  "Clang"


  version 9.0.1.
```
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

As requested at https://github.com/conan-io/conan-center-index/issues/970

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [x] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [x] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [ ] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [x] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by Croydon** [comment] 2020-03-04 01:50
Hi @alnkpa and thanks for contributing!

CI is failing for Linux right now completely: https://github.com/alnkpa/conan-quazip/actions/runs/48220989

Can we update the Qt dependencies to 5.14.1?

**Comment by alnkpa** [comment] 2020-03-04 09:39
It seems to fail on linux with

```
conans.errors.ConanException: Missing prebuilt package for 'xkbcommon/0.8.4@bincrafters/stable'
```

I'll try it with Qt 5.14.1

**Comment by alnkpa** [comment] 2020-03-04 11:54
So the GitHub actions don't build recipes that are needed but aren't available as a pre-built package. Is there a way to change that?

**Comment by Croydon** [comment] 2020-03-04 12:44
Something very weird is going on here and I fail to see what. Prebuilds for Qt should be available

Do you notice something, @ericLemanissier?

https://github.com/alnkpa/conan-quazip/runs/484523797?check_suite_focus=true#step:5:1096

My CI for Doxygen also still can't find pre-builds for Apple-Clang 11, despite it should be added and uploaded now

**Comment by Croydon** [comment] 2020-03-04 13:14
Maybe this is related to https://github.com/bincrafters/templates/pull/62

**Comment by ericLemanissier** [comment] 2020-03-04 14:49
I don't really understand what happens here. Could it be that one of the nested requirements changed a dependency version, or some default_options since the last qt stable build ?
I can't see the relation with the git autocrlf thing

**Comment by ericLemanissier** [comment] 2020-03-04 15:19
I just restarted the last stable build branch on qt repo, let's see if it makes the problem go away

**Comment by alnkpa** [comment] 2020-03-06 08:41
I tried re-triggering a build, but it fails with a similar error.

**Comment by ericLemanissier** [comment] 2020-03-11 22:00
So, windows fails because it tries to build the shared version of qt, with compiler.runtime=MT, which is not a good combination. CPT builds only MD runtime for shared libraries. It's probably a limitation of CPT, caused by the (unusual) default value of qt's shared option ?
For linux builds I'm still searching

**Comment by alnkpa** [comment] 2020-03-13 11:52
>  Edit: For linux builds, quazip CI has with_fontconfig=False whereas available qt binaries have with_fontconfig=True (the default value). This is because of this line: https://github.com/bincrafters/conan-quazip/blob/fdeafe0b5a8c488beba14bcd72e83ad07896376e/test_package/conanfile.py#L10. is it really necessary ?

This seems to be already removed in the bincrafters/conan-quazip repo

**Comment by Croydon** [comment] 2020-03-13 12:45
It wasn't but I have removed it now https://github.com/bincrafters/conan-quazip/commit/51c827d24c75c423ac76b7f2b23f0480203bce0f

**Comment by Croydon** [comment] 2020-03-13 12:50
Linux: https://github.com/bincrafters/conan-quazip/runs/505667400?check_suite_focus=true#step:5:1855

**Comment by Croydon** [comment] 2021-02-14 04:17
Closing as we are lacking active contributors for this and quazip can now be added directly to CCI

See also https://github.com/conan-io/conan-center-index/issues/970

**Closed by Croydon** 2021-02-14 04:17 UTC
Labels: packaging

**Comment by Croydon** [comment] 2021-03-03 15:58
Quazip is now available https://conan.io/center/quazip (https://github.com/conan-io/conan-center-index/pull/4562)
