### ISSUE TITLE
freetype build fails with undeclared HB_SCRIPT_ADLAM

### ISSUE THREAD

**Issue by lavinrp** [bincrafters/community#567] opened 2018-12-07 06:21 UTC
### Package Details (Include if Applicable)
* Package Name/Version: **freetype/2.9.0** AND **freetype/2.8.1**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **gcc-6.5** AND **clang-6.0**

### Steps to reproduce

> conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan 

then
> conan install freetype/2.9.0@bincrafters/stable -pr=BugReport_ConanProfile_gcc.txt --build=missing

or
> conan install freetype/2.9.0@bincrafters/stable -pr=BugReport_ConanProfile_clang.txt --build=missing

profiles and log attached to issue.
[BugReport_ConanLog.txt](https://github.com/bincrafters/community/files/2656057/BugReport_ConanLog.txt)
[BugReport_BuildErrorLog.txt](https://github.com/bincrafters/community/files/2656059/BugReport_BuildErrorLog.txt)
[BugReport_ConanProfile_clang.txt](https://github.com/bincrafters/community/files/2656060/BugReport_ConanProfile_clang.txt)
[BugReport_ConanProfile_gcc.txt](https://github.com/bincrafters/community/files/2656061/BugReport_ConanProfile_gcc.txt)

**Comment by uilianries** [comment] 2018-12-07 10:21
Thanks for reporting.

**Comment by SSE4** [comment] 2018-12-15 17:10
found a similar bug report https://github.com/mxe/mxe/issues/1865

**Comment by SSE4** [comment] 2018-12-16 12:10
@lavinrp I've pushed the fix, please give an another try

**Comment by lavinrp** [comment] 2018-12-16 17:53
@SSE4 
Thanks for the quick turnaround time. I still seem to have the issue though.

I ran the command:
`conan remove freetype/* -s -p -b -f`

Then repeated the steps from the initial bug report.
[buildError2.txt](https://github.com/bincrafters/community/files/2683802/buildError2.txt)
[BugReport_BuildErrorLog2.txt](https://github.com/bincrafters/community/files/2683803/BugReport_BuildErrorLog2.txt)

**Comment by drhodes** [comment] 2019-01-21 15:19
Hi, Maybe another data point will help. On Debian 9 stable, amd64. 

I'm new to conan and have hit this issue, or similar, while building freetype/2.8.1@bincrafters/stable as a dependency.  

The build errors with:

```
 error: expected identifier before numeric constant
/usr/include/harfbuzz/hb-common.h:317:11: note: in expansion of macro ‘HB_SCRIPT_ADLAM’
   /*9.0*/ HB_SCRIPT_ADLAM   = HB_TAG ('A','d','l','m'),
```
My concern, (perhaps unfounded), is that my system library is being included instead of what I expected to be something chased down and built by conan. 

The system library is old: libharfbuzz-dev/stable, stable, now 1.4.2-1

```
$ conan search harfbuzz -r=bincrafters
harfbuzz/1.7.1@bincrafters/stable
harfbuzz/1.7.2@bincrafters/stable
harfbuzz/1.7.6@bincrafters/stable
harfbuzz/2.3.0@bincrafters/stable
```

Please let me know if this observation should go in a separate issue, thanks.

**Comment by SSE4** [comment] 2019-02-14 19:45
@lavinrp @drhodes I've applied changes to disable harfbuzz auto-detection: https://github.com/bincrafters/conan-freetype/commit/e2e3b3e28d3bab22dd387d539dfa981828cfaaeb
could you possibly give an another try?

**Comment by drhodes** [comment] 2019-02-14 21:19
Thanks for getting back to this. I have since downgraded the toolchain on my dev box to gcc-6, but I did test your change on another box with a testing version of debian running gcc 8.2.0, and it builds fine with the following:

    $ cd cloned-conan-freetype@e2e3b3e
    $ conan source conanfile.py
    $ conan build conanfile.py

    [100%] Built target freetype

So, looks like it works now, thanks!

**Comment by SSE4** [comment] 2019-02-14 22:31
confirmed as fixed, closing

**Closed by SSE4** 2019-02-14 22:31 UTC
Labels: bug, feedback
