### ISSUE TITLE
Good practices for recipe creation

### ISSUE THREAD

**Issue by osechet** [bincrafters/community#660] opened 2019-02-26 07:24 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **GDAL**
  * Operating System+version: **Any**
  * Compiler+version: **Any**
  * Docker image: **Any**
  * Conan version: **Conan 1.12.1**
  * Python version: **Python 3.6.7**

### Question Description
I restarted the development of my recipe for GDAL (https://www.gdal.org/) and I run into some issues. I was wondering if you would have some advice for me.
1. GDAL does not allow to build out of source. In the build() method I have to reference the source folder and the whole build is done in the source folder. What is the Conan way to deal with this situation?
2. When build staticly, the GDAL library references several external libraries (such as libsqlite3). The library build succeed but linking with it fails if the others libraries are not provided. Is there an example of an other package that had to deal with this kind of things?

**Comment by uilianries** [comment] 2019-02-26 14:30
Hi @osechet !

Since GDAL uses `autotools` to build, you could use [AutoToolsBuildEnvironment](https://docs.conan.io/en/latest/reference/build_helpers/autotools.html#autotools-reference)



> 1. GDAL does not allow to build out of source. In the build() method I have to reference the source folder and the whole build is done in the source folder. What is the Conan way to deal with this situation?

We have a bunch of projects with same situation. For example:
https://github.com/bincrafters/conan-elfutils/blob/testing/0.173/conanfile.py

> 2\. When build staticly, the GDAL library references several external libraries (such as libsqlite3). The library build succeed but linking with it fails if the others libraries are not provided. Is there an example of an other package that had to deal with this kind of things?

You need to add ALL requirements on [requires](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#requires) attribute. Conan should be able to solve all requirements automatically.

Reagards!

**Comment by osechet** [comment] 2019-02-26 15:37
Hi @uilianries!
Thanks for your answer!

I'm already using AutoToolsBuildEnvironment but with the "automatic" syntax, it runs the `configure` script in the build directory so I'm forced to use the "manual" syntax to build from the source directory:
```
with tools.environment_append(autotools.vars):
    self.run("cd %s && ./configure --prefix %s %s" % (os.path.join(self.source_folder, self._folder), self.package_folder, " ".join(config_args)))
    self.run("cd %s && make" % os.path.join(self.source_folder, self._folder))
    self.run("cd %s && make install" % os.path.join(self.source_folder, self._folder))
```
It's not really clean and I was wondering if I missed something in the documentation. The `configure_dir` argument only says where to find the `configure` file.

> Conan should be able to solve all requirements automatically.
It will if I use the `${CONAN_LIBS}` variable in the `target_link_libraries()` command. However I try to use the imported target syntax since it's the recommended way to use CMake since v3.x (here is a nice article about why this syntax should be preferred: https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/). I would like to use the `requirements()` method to depend on sqlite3 only for static builds and adapt in the `test_package`'s `CMakeLists.txt` to only link with sqlite3 when staticly building.

**Comment by ericLemanissier** [comment] 2019-02-26 15:43
If you do not set the `no_copy_source` attribute of your recipe (or set it to `False`), conan automatically copies the content of the source folder in the build folder

**Comment by osechet** [comment] 2019-02-26 16:14
It isn't the behavior I get. `no_copy_source` is not set (or if I set it to False), I get:
```
GDAL/1.11.1@osechet/testing: Building your package in /sandbox/cache/conan/data/GDAL/1.11.1/osechet/testing/build/e3519d076e8b4b4c24b338746a26f420e4cad528
GDAL/1.11.1@osechet/testing: Configuring sources in /sandbox/cache/conan/data/GDAL/1.11.1/osechet/testing/source
```
It downloads the sources in the `source` directory and never copies them to the `build` directory. Then when conan calls the `build()` method it fails saying `./configure` does not exists.

If I remember well, the behavior you describe is when the conanfile is managed by the library and there no source download and you use `export_sources = "*"`. In my case the recipe and the sources are not in the same repo.

**Comment by uilianries** [comment] 2019-02-26 16:20
@osechet check the link that I sent, there you will see `tools.chdir`. Try to avoid `self.run`
Also, where we can read your recipe to make a review? I know your project is https://github.com/osechet/conan-gdal, but which branch are you using now?

**Comment by ericLemanissier** [comment] 2019-02-26 16:22
is the build folder really empty at the beginning of the `build` method ? without `no_copy_source` https://docs.conan.io/en/latest/reference/conanfile/attributes.html#no-copy-source conan should definitely copy the sources to the build folder, and it is orthogonal to `exports_sources` attribute

**Comment by osechet** [comment] 2019-02-26 16:42
@uilianries I'm working on the `testing/1.11.1` branch but I just made a `test_outofsource_build` branch to show the modifications that are described in this thread.
About the `cd` calls, it was mainly temporary until I find a solution to build in the build dir.

@ericLemanissier In my case, the sources are not copied to the build directory and thinking a little bit more about it, I'm pretty sure the sources are not copied in the case of a recipe and sources in same repo, except if you use `export_sources = "*"`. And in that case, it copies from the source of the recipe, not the source folder.

**Comment by SSE4** [comment] 2019-02-26 16:45
@osechet 
1. for in-source builds, use `tools.chdir`. for out-of-source builds use `configure_dir` argument.
2. this is complicated question and depends on how particular project is designed:
2.1. direct approach: configure script may want library to be just available somewhere in system, in this case `LDFLAGS` environment variable have to be adjusted with conan library paths, and `AutoToolsBuildEnvironment` helper automatically adjusts these variables
2.2. pkg-config approach: this requires that you have `pkg-config` (*.pc) files of your dependencies available, therefore, `PKG_CONFIG_PATH` environment variable needs to be set (use `pkg_config_paths`) parameter. as for .pc files, they might be generated by conans `pkg_config` generator, or they are usually provided by project itself, but in this case files have hard-coded paths that must be post-processed (use `tools.replace_prefix_in_pc_file` helper). this approach is my favorite, but unfortunately some libraries don't provide *.pc files (e.g. alsa).
2.3. config tool approach: some libraries, e.g. freetype, sdl2 and wxWidgets have their own pkg-config-like scripts to report required cflags/ldflags on how to link with them. then you'll need to provide 
2.4. libtool approach: via libtool *.la files, I didn't manage to have it working, unfortunately
in general, I'd start any troubleshooting by inspecting `config.log` file generated by `configure` call. it usually provides helpful traces on how particular project tries to link with particular library. it's usually trial error process, as there are many ways on how to link/depend on libraries.
good examples might be `conan-ffmpeg` (2.1, 2.2) and `conan-sdl2_ttf` (2.3) projects.

**Comment by ericLemanissier** [comment] 2019-02-26 16:51
`export_sources` attribute and `source()` method are used to fill the source folder in conan local cache. Then  

> Sources will be copied to the build/hashXXX folder, and the build() method will be triggered.

This is documented https://docs.conan.io/en/latest/creating_packages/understand_packaging.html#package-creation-process

Also note that it is critical that the source folder in conan local cache is not modified at all during the build and package method, in order to have reproducible build, so don't use attribute `no_copy_source`

**Comment by osechet** [comment] 2019-02-26 17:33
@ericLemanissier I finally understood my mistake: I forgot the sources where in a subdirectory and I was not calling configure from that directory but from the build directory's root. It's now working. Thanks!

**Comment by osechet** [comment] 2019-02-28 07:40
Thank you all for your help. It's working... almost :( In travis, some jobs fail randomly during the upload with a 405 error:
```
Error uploading file: conan_package.tgz, 'b'<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body bgcolor="white">\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n''
```
If I restart them they may pass but sometimes I have to restart them several times. I suspect some concurrency problem: the problem could happend when several jobs try to upload at the same time.
Any idea?

**Comment by SSE4** [comment] 2019-02-28 07:51
@osechet nope, just random bintray issues that happen from time to time. most of days parallel uploads work flawlessly, but sometimes it has intermittent issues on upload. so the best we can do - keep restarting jobs.

**Comment by osechet** [comment] 2019-02-28 15:49
@SSE4 Alright. Thank you.

**Comment by SSE4** [comment] 2019-02-28 15:51
@osechet okay, do we have question answered now? can we close an issue?

**Comment by osechet** [comment] 2019-02-28 16:12
@SSE4 Yes, the issue can be closed. I got all my answers :D

**Comment by SSE4** [comment] 2019-02-28 16:13
confirmed as answered, closing

**Closed by SSE4** 2019-02-28 16:13 UTC
Labels: question
