### ISSUE TITLE
How to download updated recipe (boost_generator)

### ISSUE THREAD

**Issue by ruurdadema** [bincrafters/community#836] opened 2019-06-19 06:58 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost_generator/1.69.0@bincrafters/stable**
  * Operating System+version: **macOS 10.14.4 (18E226)**
  * Compiler+version: **Apple LLVM version 10.0.1 (clang-1001.0.46.4)**
  * Docker image: **n/a**
  * Conan version: **Conan version 1.15.0**
  * Python version: **Python 3.7.2**

### Question Description
After patch https://github.com/bincrafters/conan-boost_generator/commit/db89a08b36e2233689420d62a0b59b20a3ead025 was applied to fix issue #794 I had a hard time figuring out how to download the updated package to test the patch.
I ended up manually deleting ~/.conan/data/boost_generator and ~/.conan/data/boost_filesystem, the latter to trigger download of the former.

I also tried to `conan install -s os.version=10.11 --build=missing --update` but this did not work. (because boost_generator is not specified in my conan file and is just a requirement for the boost_* packages?)

What would be the recommended procedure in this case to follow upstream updates?

Thanks.

**Comment by SSE4** [comment] 2019-06-19 08:42
@ruurdadema this seems to be a conan issue. do you have a reproducible example? if so, please open an issue here: https://github.com/conan-io/conan/issues

**Comment by ruurdadema** [comment] 2019-06-26 13:41
I'll have to think about that as this I think this is hard to reproduce. Do you have any suggetions?

**Comment by SSE4** [comment] 2019-07-02 09:35
sorry, I have no idea, unfortunately. you may just open an issue and ask conan developers for the advice.

**Comment by Croydon** [comment] 2019-08-09 12:08
I'm going to close this as it appears to be no Bincrafters specific issue.

If you have general Conan issues please open an issue in the Conan issue tracker, thanks!

**Closed by Croydon** 2019-08-09 12:08 UTC
Labels: question
