### ISSUE TITLE
Inclusion Request: libfvad

### ISSUE THREAD

**Issue by TMiguelT** [bincrafters/community#620] opened 2019-01-24 14:18 UTC
### Package Details
  * Package Name: **libfvad**
  * Operating Systems+versions: **Linux Ubuntu 16.04, Ubuntu 18.04, Windows, macOS**
  * Compiler support: **gcc-5.4, gcc6, clang7**
  * Conan recipe repository: **https://github.com/TMiguelT/conan-libfvad**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/conan-templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [ ] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

I've done most of the work in packaging this. However, I can't get my example file to link properly, I'm getting:
```
[100%] Linking CXX executable bin/test_package
/usr/bin/cmake -E cmake_link_script CMakeFiles/test_package.dir/link.txt --verbose=1
/usr/bin/c++    -m64 -O3 -DNDEBUG        -rdynamic CMakeFiles/test_package.dir/test_package.cpp.o  -o bin/test_package  -L/home/michael/.conan/data/libfvad/1.0/tmiguelt/test/package/d351525cc53ebe68279edf1978846402420066e7/lib -Wl,-rpath,/home/michael/.conan/data/libfvad/1.0/tmiguelt/test/package/d351525cc53ebe68279edf1978846402420066e7/lib -lfvad 
CMakeFiles/test_package.dir/test_package.cpp.o: In function `main':
test_package.cpp:(.text.startup+0x2): undefined reference to `fvad_new()'
test_package.cpp:(.text.startup+0x12): undefined reference to `fvad_set_mode(Fvad*, int)'
test_package.cpp:(.text.startup+0x1a): undefined reference to `fvad_free(Fvad*)'
collect2: error: ld returned 1 exit status
CMakeFiles/test_package.dir/build.make:97: recipe for target 'bin/test_package' failed
```

Also, since libfvad is actually a subset from another project ([webrtc](https://webrtc.googlesource.com/src)), which do I set as the homepage of the project? 

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [ ] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [ ] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [ ] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [ ] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by SSE4** [comment] 2019-01-24 14:22
@TMiguelT in order to solve linking issues, have you tried to add `extern "C"` around here? https://github.com/TMiguelT/conan-libfvad/blob/master/test_package/test_package.cpp#L2

**Comment by uilianries** [comment] 2019-01-24 14:25
@TMiguelT the author's license looks like be "BSD-3-Clause"

**Comment by TMiguelT** [comment] 2019-01-24 14:34
And the license should now be correct

**Comment by TMiguelT** [comment] 2019-01-24 14:38
@uilianries 
Can you elaborate on those last two points? I can't find anywhere that `self.settings.compiler.libcxx` is added as a setting. Is it a default? How do I remove it?

Also I'm not really sure if the library is compatible with Windows. Should I set up an appveyor build to find out?

**Comment by uilianries** [comment] 2019-01-24 14:42
> Can you elaborate on those last two points? I can't find anywhere that self.settings.compiler.libcxx is added as a setting. Is it a default? How do I remove it?

Just add the follow statement  in your recipe:

```python
    def configure(self):
        del self.settings.compiler.libcxx
```

The idea is ignoring libcxx (lic++, libstdc++, libstdc++11) from your package id.

**Comment by uilianries** [comment] 2019-01-24 14:47
The second point, if confirmed that fvad does not work on Windows:

```python
from conans.error import ConanInvalidConfiguration
...
    def configure(self):
        if self.settings.os == "Windows":
            raise ConanInvalidConfiguration("fvad is not supported on Windows")
```

Otherwise, if is not supported on OSX:

```python
from conans.error import ConanInvalidConfiguration
...
    def configure(self):
        if self.settings.os == "Macos":
            raise ConanInvalidConfiguration("fvad is not supported on Macos")
```

Or even the compiler Visual Studio:

```python
from conans.error import ConanInvalidConfiguration
...
    def configure(self):
        if self.settings.compiler == "Visual Studio":
            raise ConanInvalidConfiguration("fvad is not supported for Visual Studio")
```

**Comment by TMiguelT** [comment] 2019-01-24 22:07
Great, thanks for the examples. But I'm still not really sure how to check if it's Windows/OSX compatible without having those operating systems

**Comment by uilianries** [comment] 2019-01-24 22:14
You can set up the CI environment (Travis and Appveyor) and check the results. Do you know how to setup? Otherwise I could fork your project try by myself.

**Comment by TMiguelT** [comment] 2019-01-24 23:04
I've set up the builds:
https://ci.appveyor.com/project/TMiguelT/conan-libfvad
https://travis-ci.org/TMiguelT/conan-libfvad/builds/484120999

The Windows one fails because it doesn't understand the configure script. I guess any autotools project is going to fail on Windows (?)

**Comment by TMiguelT** [comment] 2019-01-25 00:16
Okay, I've removed the Windows builds, and got all the Mac and Linux builds working. Anything else I need to do?

**Comment by uilianries** [comment] 2019-01-25 00:48
my fault, I didn't comment before.

**Comment by uilianries** [comment] 2019-01-25 00:54
@TMiguelT  https://github.com/TMiguelT/conan-libfvad/pull/1

**Comment by TMiguelT** [comment] 2019-01-25 03:13
Merged, and it looks like everything is building fine. What now?

**Comment by uilianries** [comment] 2019-01-25 11:31
@TMiguelT Your project is now part of Bincrafters :1st_place_medal: 

https://github.com/bincrafters/conan-libfvad

All yours commits and name were preserved! Also, you were included as collaborator, thus you have permission to edit the project directly.

I'm waiting for CI to promote the project in a stable branch and publish all artifacts on Bintray.

Thanks for all your effort!

I gonna close this issue to publish all stuff!

**Comment by TMiguelT** [comment] 2019-01-25 11:36
Great, thank you!

**Comment by uilianries** [comment] 2019-01-25 12:01
Hi again!

The package is available here:
https://bintray.com/bincrafters/public-conan/libfvad%3Abincrafters

I've requested the Conan Center inclusion too!

All artifacts were uploaded with success!

![libfvad/1.0@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/76273f2e-a4cd-40e5-99ff-3b825805813e.png)

Regards!

**Closed by uilianries** 2019-01-25 12:01 UTC
Labels: Packaging
