### ISSUE TITLE
new gtest release - support options no_main and debug_postfix

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#111] opened 2018-02-12 19:22 UTC
gtest has stopped making official github releases.  They have moved to a "live at head" philosophy.  Thus, there have been many patches and improvements made to gtest since the 1.8.0 release, and users have requested a package containing these latest changes. 

In order to continue releasing modern versions of the `gtest` package on Conan, we will now begin using our "datestamp-commit" release scheme.  This is documented here: 
http://bincrafters.readthedocs.io/en/latest/using_packages.html#packages-without-semantic-versioning

**Comment by ArekPiekarz** [comment] 2018-02-13 21:37
Just curious, have Google said explicitly there will be no new tagged release for GoogleTest? From what I've read there is only silence on this matter from their side. See https://github.com/google/googletest/issues/1079 and https://github.com/google/googletest/issues/1342.

**Comment by SylvainCorlay** [comment] 2018-03-13 23:32
> They have moved to a "live at head" philosophy.

I did not see confirmed information supporting that claim on google's side.

**Comment by SylvainCorlay** [comment] 2018-03-28 13:21
@solvingj it seems that there **will** be a 1.9 as per the following issue by the current googletest maintainer:

https://github.com/google/googletest/issues/1366

So the claim that gtest has moved to a "live at head" mode appears to be false.

**Comment by solvingj** [comment] 2018-03-29 22:58
indeed it does. that's great news. we'll keep an eye out for the 1.9 release and publish it asap.  Thanks very much for bringing this up and getting confirmation.

**Comment by SSE4** [comment] 2018-05-11 01:48
still no 1.9.0 release - waiting

**Comment by SSE4** [comment] 2018-08-31 17:17
1.8.1 just released

**Comment by uilianries** [comment] 2018-09-02 16:33
I just bumped GTest to 1.8.1

https://github.com/bincrafters/conan-gtest/tree/testing/1.8.1
https://travis-ci.org/bincrafters/conan-gtest/builds/423645696
https://ci.appveyor.com/project/BinCrafters/conan-gtest/build/1.0.84

**Comment by uilianries** [comment] 2018-09-02 21:33
We have some error building on MSVC 12:

> C:\Users\appveyor\.conan\data\gtest\1.8.1\bincrafters\testing\package\f84b2d17334e7b23564f7244508491e451d80357\include\gtest/gtest-printers.h(1036): error C2770: invalid explicit template argument(s) for 'AddReference<const ::std::tr1::tuple_element<I,std::tuple<bool,int>>::type>::type testing::internal::TuplePolicy<Tuple>::get(const std::tuple<bool,int> &)' [C:\projects\conan-gtest\test_package\build\ffafa1fe0219c44dbe68adf8ffbfd78683edb626\test_package.vcxproj]

I tried to use some custom defines, as `GTEST_HAS_TR1_TUPLE` and`GTEST_USE_OWN_TR1_TUPLE` but didn't work. Also, I removed all patches from 1.8.0 because they were merged in 1.8.1.

Any ideas?

**Comment by SSE4** [comment] 2018-09-03 04:41
@uilianries let's open an issue on GoogleTest GitHub

**Comment by uilianries** [comment] 2018-09-04 21:44
Related issue: https://github.com/google/googletest/issues/1810

**Comment by uilianries** [comment] 2018-09-05 12:39
Well, according GTest community, MSVC 12 is not supported and won't be. So we could exclude from the recipe.

**Comment by uilianries** [comment] 2018-09-05 14:56
Done!

![gtest/1.8.1](https://screenshotscdn.firefoxusercontent.com/images/168c38dd-473b-4cf2-8776-bb0667231f5a.png)

https://github.com/bincrafters/conan-gtest/tree/stable/1.8.1
https://travis-ci.org/bincrafters/conan-gtest/builds/424801313
https://ci.appveyor.com/project/BinCrafters/conan-gtest/build/1.0.93

**Comment by SSE4** [comment] 2018-09-07 07:37
closing, as 1.8.1 is available on bintray

**Comment by Croydon** [comment] 2018-09-07 12:16
This issue was about the new options no_main and debug_postfix which aren't implemented yet?

**Comment by SSE4** [comment] 2018-09-07 13:35
@Croydon you're right :) sorry for the inconveniences

**Comment by uilianries** [comment] 2018-11-13 23:06
Hello everybody!

Gtest 1.8.1 is updated with `no_main` and `debug_postfix` options

Please, update your local copies.

![gtest/1.8.1@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/1dabd4cb-d2d0-43bb-8301-8d5e5ac5347f.png)

**Comment by SSE4** [comment] 2018-11-21 10:32
I am closing this for now, as we have new gtest release, and requested options implemented

**Closed by SSE4** 2018-11-21 10:32 UTC
Labels: enhancement, feedback
