### ISSUE TITLE
Upstream Update: SDL_ttf 2.0.15

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#622] opened 2019-01-25 15:32 UTC
### Package Details
  * Package Name: SDL_tff
  * Latest available Version: 2.0.15

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

## 2.0.15 should use FreeType 2.9.1 and is therefore blocked on #621 

``` Changes in this release:
 * Updated to FreeType version 2.9.1
 * Text rendering functions now use the alpha component of the text colors
 * Added support for characters greater than 0xFFFF (e.g. emoji) in the UTF-8 APIs
```

**Comment by SSE4** [comment] 2019-02-03 01:15
fails with:
```
configure: WARNING:
  The freetype-config script installed by FreeType 2 could not be found.
  If FreeType 2 was installed in PREFIX, make sure PREFIX/bin is in
  your path, or set the FT2_CONFIG environment variable to the
  full path to freetype-config.
       
configure: error: *** Unable to find FreeType2 library (http://www.freetype.org/)
```
https://travis-ci.com/bincrafters/conan-sdl2_ttf/jobs/174906745
out FreeType build seems to be missing `freetype-config`

**Comment by uilianries** [comment] 2019-02-04 10:38
Thanks for reporting @SSE4

**Comment by SSE4** [comment] 2019-02-14 13:01
seems like regression, they try to look for freetype>=7.0.1:
```
configure:12002: $PKG_CONFIG --exists --print-errors "freetype2 >= 7.0.1"
Requested 'freetype2 >= 7.0.1' but version of FreeType 2 is 2.9.1
You may find new versions of FreeType 2 at http://freetype.org
configure:12005: $? = 1
configure:12020: $PKG_CONFIG --exists --print-errors "freetype2 >= 7.0.1"
Requested 'freetype2 >= 7.0.1' but version of FreeType 2 is 2.9.1
You may find new versions of FreeType 2 at http://freetype.org
configure:12023: $? = 1
Requested 'freetype2 >= 7.0.1' but version of FreeType 2 is 2.9.1
You may find new versions of FreeType 2 at http://freetype.org
configure:12051: result: no
configure:12142: checking for freetype-config
configure:12175: result: no
configure:12197: checking for FreeType -- version >= 7.0.1
configure:12299: result: no
configure:12308: WARNING:

  The freetype-config script installed by FreeType 2 could not be found.
  If FreeType 2 was installed in PREFIX, make sure PREFIX/bin is in
  your path, or set the FT2_CONFIG environment variable to the
  full path to freetype-config.

configure:12354: error: *** Unable to find FreeType2 library (http://www.freetype.org/)
```
anyway, I am going to provide `freetype-config` in freetype just to have a complete package

**Comment by SSE4** [comment] 2019-02-14 14:01
this page has more insight on it: https://github.com/aseprite/freetype2/blob/master/docs/VERSIONS.TXT
seems like there are different versioning schemes

**Comment by SSE4** [comment] 2019-02-14 14:13
I've pushed required changes, https://github.com/bincrafters/conan-freetype/commit/aef0a8a8997e2d9d5ea9d238780545b06d958b62, it builds locally, hope to get sdl2_ttf builds soon

**Comment by SSE4** [comment] 2019-02-15 10:25
new binaries are available, closing

**Closed by SSE4** 2019-02-15 10:25 UTC
Labels: Upstream Update
