### ISSUE TITLE
[sdl2_mixer] SDL2 Mixer don't compile on macos

### ISSUE THREAD

**Issue by prsolucoes** [bincrafters/community#865] opened 2019-07-06 12:34 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl2_mixer/2.0.5**
  * Operating System+version: **macos mojave**
  * Compiler+version: **clang-10**
  * Conan version: **conan 1.16.1**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
conan profile show default
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

```
from conans import ConanFile, CMake


class TargetConan(ConanFile):
    name = 'macos_app'
    version = '1.0.0'
    settings = 'os', 'compiler', 'build_type', 'arch'
    options = {
        'shared': [True, False],
        'fPIC': [True, False],
    }
    default_options = {
        'shared': False,
        'fPIC': True,
        'sdl2_image:bmp': False,
        'sdl2_image:gif': False,
        'sdl2_image:lbm': False,
        'sdl2_image:pcx': False,
        'sdl2_image:pnm': False,
        'sdl2_image:svg': False,
        'sdl2_image:tga': False,
        'sdl2_image:xcf': False,
        'sdl2_image:xpm': False,
        'sdl2_image:xv': False,
        'sdl2_image:jpg': 'libjpeg',
        'sdl2_image:tif': False,
        'sdl2_image:png': True,
        'sdl2_image:webp': False,
    }
    exports_sources = '*'
    generators = 'cmake'

    def build(self):
        cmake = CMake(self)
        cmake.definitions['CMAKE_BUILD_TYPE'] = self.settings.build_type
        cmake.definitions['PROJECT_CONFIG_ARCH'] = self.settings.arch
        cmake.definitions['CMAKE_OSX_DEPLOYMENT_TARGET'] = self.settings.get_safe("os.version")
        cmake.configure()
        cmake.build()

    def requirements(self):
        self.requires('sdl2/2.0.9@bincrafters/stable')
        self.requires('sdl2_image/2.0.4@bincrafters/stable')
        self.requires('sdl2_ttf/2.0.15@bincrafters/stable')
        self.requires('sdl2_mixer/2.0.4@bincrafters/stable')
        self.requires('libpng/1.6.36@bincrafters/stable')

```

### Logs (Include/Attach if Applicable)

```
[ 93%] Building C object src/CMakeFiles/libfluidsynth-OBJ.dir/bindings/fluid_ladspa.c.o
[ 93%] Built target libfluidsynth-OBJ
Scanning dependencies of target libfluidsynth
[ 95%] Linking C static library ../lib/libfluidsynth.a
[ 95%] Built target libfluidsynth
Scanning dependencies of target fluidsynth
[ 97%] Building C object src/CMakeFiles/fluidsynth.dir/fluidsynth.c.o
[100%] Linking C executable ../bin/fluidsynth
Undefined symbols for architecture x86_64:
  "_g_libintl_bind_textdomain_codeset", referenced from:
      _ensure_gettext_initialized in libglib-2.0.a(ggettext.c.o)
  "_g_libintl_bindtextdomain", referenced from:
      _ensure_gettext_initialized in libglib-2.0.a(ggettext.c.o)
  "_g_libintl_dcgettext", referenced from:
      _g_dcgettext in libglib-2.0.a(ggettext.c.o)
  "_g_libintl_dgettext", referenced from:
      _g_dgettext in libglib-2.0.a(ggettext.c.o)
  "_g_libintl_dngettext", referenced from:
      _g_dngettext in libglib-2.0.a(ggettext.c.o)
  "_g_libintl_gettext", referenced from:
      __g_dgettext_should_translate in libglib-2.0.a(ggettext.c.o)
  "_g_libintl_textdomain", referenced from:
      __g_dgettext_should_translate in libglib-2.0.a(ggettext.c.o)
  "_iconv", referenced from:
      _g_iconv in libglib-2.0.a(gconvert.c.o)
     (maybe you meant: _g_convert_with_iconv, _g_iconv , _g_iconv_open , _g_iconv_close )
  "_iconv_close", referenced from:
      _g_iconv_close in libglib-2.0.a(gconvert.c.o)
     (maybe you meant: _g_iconv_close)
  "_iconv_open", referenced from:
      _try_conversion in libglib-2.0.a(gconvert.c.o)
     (maybe you meant: _g_iconv_open)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [src/CMakeFiles/fluidsynth.dir/build.make:87: bin/fluidsynth] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:198: src/CMakeFiles/fluidsynth.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2
fluidsynth/2.0.5@bincrafters/stable: 
fluidsynth/2.0.5@bincrafters/stable: ERROR: Package 'cb72c2615647dba8855397b313b81b5317587763' build failed
fluidsynth/2.0.5@bincrafters/stable: WARN: Build folder /Users/paulo/.conan/data/fluidsynth/2.0.5/bincrafters/stable/build/cb72c2615647dba8855397b313b81b5317587763
ERROR: fluidsynth/2.0.5@bincrafters/stable: Error in build() method, line 157
	cmake.build()
	ConanException: Error 512 while executing cmake --build '/Users/paulo/.conan/data/fluidsynth/2.0.5/bincrafters/stable/build/cb72c2615647dba8855397b313b81b5317587763/build_subfolder' '--' '-j4'
COMMAND: conan install /Users/paulo/Developer/workspaces/cpp/ezored-sdl2/files/targets/macos_app/conan/recipe/conanfile.py --profile ezored_macos_app_profile -s arch=x86_64 -s os.version=10.9 -s build_type=Debug --build=missing --update
WORKING DIR: /Users/paulo/Developer/workspaces/cpp/ezored-sdl2/build/macos_app/Debug/x86_64/conan
[ERROR] Command execution has failed
```

**Comment by SSE4** [comment] 2019-07-09 09:08
interesting, as it passed on CI. I'll take a look

**Comment by SSE4** [comment] 2019-07-18 20:37
yeah, reproduced the same, will try to fix

**Comment by SSE4** [comment] 2019-08-07 08:41
duplicate of https://github.com/bincrafters/community/issues/899

**Closed by SSE4** 2019-08-07 08:41 UTC
Labels: bug
