### ISSUE TITLE
[glib] build from source failed on MacOS Mojave, Apple Clang 11

### ISSUE THREAD

**Issue by BlueSolei** [bincrafters/community#992] opened 2019-10-07 23:17 UTC
### Package and Environment Details 
  * Package: **glib/2.58.3@bincrafters/stable**
  * Operating System: **MacOS Mojave 10.14.6**
  * Compiler: **Apple Clang 11.0**
  * Conan: **1.19.1**
  * Python: **3.7.4**

### Conan profile 
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce
conan install glib/2.58.3@bincrafters/stable --build glib

### Logs 
see in [output log](https://github.com/bincrafters/community/files/3699983/InstallGLib.txt): 
The error: **meson.build:612:2: ERROR: Unknown compiler(s): ['cc']**
But it did find it: **Native C compiler: cc (clang 11.0.0 "Apple clang version 11.0.0 (clang-1100.0.33.8)")**
And in terminal calling `cc` works.

[meson-log.txt](https://github.com/bincrafters/community/files/3699981/meson-log.txt)

**Comment by ericLemanissier** [comment] 2019-10-20 18:11
this seems to be a duplicate of https://github.com/bincrafters/community/issues/976

**Closed** 2019-10-21 17:00 UTC
Labels: bug
