### ISSUE TITLE
gyp_installer TypeError: '>=' not supported between instances of 'tuple' and 'str'

### ISSUE THREAD

**Issue by sourcedelica** [bincrafters/community#730] opened 2019-04-11 16:29 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **gyp_installer/20181217**
  * Operating System+version: **MacOS 10.14.4**
  * Compiler+version: **Apple clang 10.0.1**
  * Conan version: **conan 1.14.3**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` 
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
`conan install LibUV/1.25.0@bincrafters/stable --build LibUV`

Trying to build `LibUV` with Apple clang 10.0.1 I get an error in `gyp_installer` (see log).

### Logs (Include/Attach if Applicable)
```
$ conan install LibUV/1.25.0@bincrafters/stable --build LibUV

LibUV/1.25.0@bincrafters/stable: WARN: Forced build from source
Installing package: LibUV/1.25.0@bincrafters/stable
Requirements
    LibUV/1.25.0@bincrafters/stable from local cache - Cache
Packages
    LibUV/1.25.0@bincrafters/stable:bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583 - Build
Build requirements
    gyp_installer/20181217@bincrafters/stable from 'conan-center' - Cache
Build requirements packages
    gyp_installer/20181217@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

gyp_installer/20181217@bincrafters/stable: Already installed!
LibUV/1.25.0@bincrafters/stable: Applying build-requirement: gyp_installer/20181217@bincrafters/stable
LibUV/1.25.0@bincrafters/stable: WARN: Build folder is dirty, removing it: /Users/eric/.conan/data/LibUV/1.25.0/bincrafters/stable/build/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583
LibUV/1.25.0@bincrafters/stable: Copying sources to build folder
LibUV/1.25.0@bincrafters/stable: Building your package in /Users/eric/.conan/data/LibUV/1.25.0/bincrafters/stable/build/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583
LibUV/1.25.0@bincrafters/stable: Generator cmake created conanbuildinfo.cmake
LibUV/1.25.0@bincrafters/stable: Calling build()
['-f', 'ninja', '-Dtarget_arch=x64', '-Duv_library=static_library', '-I', 'common.gypi', 'test/test.gyp', '--depth=.', '-Dhost_arch=x64']
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/eric/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/eric/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/eric/.conan/data/gyp_installer/20181217/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/pylib/gyp/generator/ninja.py", line 2467, in CallGenerateOutputForConfig
    GenerateOutputForConfig(target_list, target_dicts, data, params, config_name)
  File "/Users/eric/.conan/data/gyp_installer/20181217/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/pylib/gyp/generator/ninja.py", line 2405, in GenerateOutputForConfig
    target = writer.WriteSpec(spec, config_name, generator_flags)
  File "/Users/eric/.conan/data/gyp_installer/20181217/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/pylib/gyp/generator/ninja.py", line 486, in WriteSpec
    spec)
  File "/Users/eric/.conan/data/gyp_installer/20181217/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/pylib/gyp/generator/ninja.py", line 925, in WriteSources
    precompiled_header, spec)
  File "/Users/eric/.conan/data/gyp_installer/20181217/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/pylib/gyp/generator/ninja.py", line 995, in WriteSourcesForArch
    env = self.GetToolchainEnv()
  File "/Users/eric/.conan/data/gyp_installer/20181217/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/pylib/gyp/generator/ninja.py", line 1402, in GetToolchainEnv
    env = self.GetSortedXcodeEnv(additional_settings=additional_settings)
  File "/Users/eric/.conan/data/gyp_installer/20181217/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/pylib/gyp/generator/ninja.py", line 1420, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/eric/.conan/data/gyp_installer/20181217/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/pylib/gyp/xcode_emulation.py", line 1751, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/eric/.conan/data/gyp_installer/20181217/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/pylib/gyp/xcode_emulation.py", line 1664, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
```

**Comment by SSE4** [comment] 2019-04-22 09:11
@uilianries may you take a look?

**Comment by uilianries** [comment] 2019-04-23 12:24
Yes, I'll take a look

**Comment by uilianries** [comment] 2019-04-23 12:50
That's weird, I can't reproduce the same error, using a very similar scenario:

#### Enviroment

System Version: macOS 10.14.4 (18E226)
Kernel Version: Darwin 18.5.0
Python 3.7.0]
Clang: Apple LLVM version 10.0.1
Conan: 1.14.3

```shell
$ conan install libuv/1.25.0@bincrafters/stable --build libuv -r bincrafters
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

libuv/1.25.0@bincrafters/stable: WARN: Forced build from source
Installing package: libuv/1.25.0@bincrafters/stable
Requirements
    libuv/1.25.0@bincrafters/stable from 'bincrafters' - Cache
Packages
    libuv/1.25.0@bincrafters/stable:bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583 - Build
Build requirements
    gyp_installer/20181217@bincrafters/stable from 'bincrafters' - Cache
    ninja_installer/1.8.2@bincrafters/stable from 'conan-center' - Cache
Build requirements packages
    gyp_installer/20181217@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    ninja_installer/1.8.2@bincrafters/stable:743cf0321be3152777da4d05247a66d1552e70a2 - Cache

gyp_installer/20181217@bincrafters/stable: Already installed!
ninja_installer/1.8.2@bincrafters/stable: Already installed!
libuv/1.25.0@bincrafters/stable: Applying build-requirement: gyp_installer/20181217@bincrafters/stable
libuv/1.25.0@bincrafters/stable: Applying build-requirement: ninja_installer/1.8.2@bincrafters/stable
libuv/1.25.0@bincrafters/stable: Copying sources to build folder
libuv/1.25.0@bincrafters/stable: Building your package in /Users/user153599/.conan/data/libuv/1.25.0/bincrafters/stable/build/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583
libuv/1.25.0@bincrafters/stable: Generator cmake created conanbuildinfo.cmake
libuv/1.25.0@bincrafters/stable: Calling build()
['-f', 'ninja', '-Dtarget_arch=x64', '-Duv_library=static_library', '-I', 'common.gypi', 'test/test.gyp', '--depth=.', '-Dhost_arch=x64']
ninja: Entering directory `out/Release'
[204/204] LINK run-benchmarks, POSTBUILDS
libuv/1.25.0@bincrafters/stable: Package 'bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583' built
libuv/1.25.0@bincrafters/stable: Build folder /Users/user153599/.conan/data/libuv/1.25.0/bincrafters/stable/build/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583
libuv/1.25.0@bincrafters/stable: Generated conaninfo.txt
libuv/1.25.0@bincrafters/stable: Generated conanbuildinfo.txt
libuv/1.25.0@bincrafters/stable: Generating the package
libuv/1.25.0@bincrafters/stable: Package folder /Users/user153599/.conan/data/libuv/1.25.0/bincrafters/stable/package/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583
libuv/1.25.0@bincrafters/stable: Calling package()
libuv/1.25.0@bincrafters/stable package(): Packaged 16 '.h' files
libuv/1.25.0@bincrafters/stable package(): Packaged 1 '.a' file: libuv.a
libuv/1.25.0@bincrafters/stable package(): Packaged 2 files: LICENSE, LICENSE-docs
libuv/1.25.0@bincrafters/stable: Package 'bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583' created
libuv/1.25.0@bincrafters/stable: Created package revision bc417dc1030d0fc12830ee90424954a8
```

Anyway, it's to understand that `XcodeVersion` is returning a tuple which can't be checked against a string. I'll provide a patch to convert that return in a string.

**Comment by uilianries** [comment] 2019-04-23 12:54
@sourcedelica Where did you find LibUV? Bincrafters only provides **libuv**. As you are running a Unix system the match case matters.

**Comment by uilianries** [comment] 2019-04-23 13:50
We will need two PRs:

GYP: https://github.com/bincrafters/gyp/pull/3
Conan Gyp Installer: TODO

**Comment by uilianries** [comment] 2019-04-23 17:38
@sourcedelica A new version is available. Please, update and try again:

    conan install --update --remote bincrafters libuv/1.25.0@bincrafters/stable

**Comment by SSE4** [comment] 2019-06-03 08:26
changes were applied, closing

**Closed by SSE4** 2019-06-03 08:26 UTC
Labels: bug, feedback, fixed
