### ISSUE TITLE
[Qt 5.x.x] Libraries are not available through conan_libs variable

### ISSUE THREAD

**Issue by p-groarke** [bincrafters/community#323] opened 2018-06-20 16:09 UTC
Using latest conan (1.4.4), VS 2017, win10.
Using cmake_multi generator and conan targets.

Getting unresolved symbols linking with CONAN_PKG::Qt. Attached is a minimal example to repro the issue.
[qt_conan.zip](https://github.com/bincrafters/community/files/2120157/qt_conan.zip)

On a side note, will AUTOMOC and AUTOUIC find Qt5Widgets when using conan targets?

**Comment by p-groarke** [comment] 2018-06-20 16:10
@lucienboillod as discussed on slack

**Comment by lucienboillod** [comment] 2018-06-21 08:39
Hello :smile: 
can you please describe the exacts steps to reproduce ? command lines etc ...
attached with a log of you error.

I am not getting the same error for now

**Comment by ShamanTcler** [comment] 2018-06-21 12:07
I was replicating this in Qt 5.9.6 using MSVS 2015 ( compiler 14 ) on Win 10
Using his zip. Changed to Qt/5.9.6@bincrafters/stable

Created a build dir and cd'd to it (out of source build)
>conan install ..  -s build_type=Debug
>cmake .. -G Ninja
>ninja

qt_test_tests.exe : fatal error LNK1120: 9 unresolved externals

That's what I did at least.

**Comment by p-groarke** [comment] 2018-06-22 14:00
Here are logs:

```
C:\Users\pgroarke\code\experiments\qt_conan\build>cmake .. -A x64 && cmake --build .
-- Building for: Visual Studio 15 2017
-- The CXX compiler identification is MSVC 19.14.26428.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Current conanbuildinfo.cmake directory: C:/Users/pgroarke/code/experiments/qt_conan/build
-- Conan: Using cmake targets configuration
-- Library gmock_main found C:/Users/pgroarke/.conan/data/gtest/1.8.0/bincrafters/stable/package/f6b9d4145acda2f4ee1d45f23527c7e694ee420b/lib/gmock_main.lib
-- Library gmock found C:/Users/pgroarke/.conan/data/gtest/1.8.0/bincrafters/stable/package/f6b9d4145acda2f4ee1d45f23527c7e694ee420b/lib/gmock.lib
-- Library gtest found C:/Users/pgroarke/.conan/data/gtest/1.8.0/bincrafters/stable/package/f6b9d4145acda2f4ee1d45f23527c7e694ee420b/lib/gtest.lib
-- Library gmock_main found C:/Users/pgroarke/.conan/data/gtest/1.8.0/bincrafters/stable/package/3f7b6d42d6c995a23d193db1f844ed23ae943226/lib/gmock_main.lib
-- Library gmock found C:/Users/pgroarke/.conan/data/gtest/1.8.0/bincrafters/stable/package/3f7b6d42d6c995a23d193db1f844ed23ae943226/lib/gmock.lib
-- Library gtest found C:/Users/pgroarke/.conan/data/gtest/1.8.0/bincrafters/stable/package/3f7b6d42d6c995a23d193db1f844ed23ae943226/lib/gtest.lib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/pgroarke/code/experiments/qt_conan/build
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2018-06-22 9:58:57 AM.
Project "C:\Users\pgroarke\code\experiments\qt_conan\build\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "C:\Users\pgroarke\code\experiments\qt_conan\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\pgroarke\code\e
xperiments\qt_conan\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\ZERO_CHECK\".
  Creating directory "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because C:/Users/pgroarke/code/experiments/qt_conan/build/CMakeFiles/generate.stamp is
  up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\Users\pgroarke\code\experiments\qt_conan\build\ZERO_CHECK.vcxproj" (default targets).

Project "C:\Users\pgroarke\code\experiments\qt_conan\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\pgroarke\code\e
xperiments\qt_conan\build\qt_test_tests.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "qt_test_tests.dir\Debug\".
  Creating directory "C:\Users\pgroarke\code\experiments\qt_conan\build\Debug\".
  Creating directory "qt_test_tests.dir\Debug\qt_test_tests.tlog\".
InitializeBuildStatus:
  Creating "qt_test_tests.dir\Debug\qt_test_tests.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Building Custom Rule C:/Users/pgroarke/code/experiments/qt_conan/CMakeLists.txt
  CMake does not need to re-run because C:/Users/pgroarke/code/experiments/qt_conan/build/CMakeFiles/generate.stamp is
  up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\CL.exe /c /IC
  :\Users\pgroarke\.conan\data\gtest\1.8.0\bincrafters\stable\package\f6b9d4145acda2f4ee1d45f23527c7e694ee420b\include
  /IC:\.conan\20e7x7t5\1\include /Zi /nologo /W4 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D NOMINMAX /D
   GTEST_LANG_CXX11=1 /D GTEST_HAS_TR1_TUPLE=0 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:preci
  se /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++14 /Fo"qt_test_tests.dir\Debug\\" /Fd"qt_test_tests.dir\Debug\vc14
  1.pdb" /Gd /TP /FC /errorReport:queue  /Zc:__cplusplus /permissive- C:\Users\pgroarke\code\experiments\qt_conan\src\m
  ain.cpp
  main.cpp
c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(327): warning C4127: conditional expression is constant [C:\Users\pgroark
e\code\experiments\qt_conan\build\qt_test_tests.vcxproj]
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(327): note: consider using 'if constexpr' statement instead
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(326): note: while compiling class template member function 'void QVecto
  r<int>::copyConstruct(const T *,const T *,T *)'
          with
          [
              T=int
          ]
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(510): note: see reference to function template instantiation 'void QVec
  tor<int>::copyConstruct(const T *,const T *,T *)' being compiled
          with
          [
              T=int
          ]
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(504): note: while compiling class template member function 'QVector<int
  >::QVector(std::initializer_list<T>)'
          with
          [
              T=int
          ]
  c:\.conan\20e7x7t5\1\include\qtcore\qversionnumber.h(142): note: see reference to function template instantiation 'QV
  ector<int>::QVector(std::initializer_list<T>)' being compiled
          with
          [
              T=int
          ]
  c:\.conan\20e7x7t5\1\include\qtcore\qabstractitemmodel.h(244): note: see reference to class template instantiation 'Q
  Vector<int>' being compiled
c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(311): warning C4127: conditional expression is constant [C:\Users\pgroark
e\code\experiments\qt_conan\build\qt_test_tests.vcxproj]
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(311): note: consider using 'if constexpr' statement instead
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(310): note: while compiling class template member function 'void QVecto
  r<int>::defaultConstruct(T *,T *)'
          with
          [
              T=int
          ]
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(567): note: see reference to function template instantiation 'void QVec
  tor<int>::defaultConstruct(T *,T *)' being compiled
          with
          [
              T=int
          ]
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(527): note: while compiling class template member function 'void QVecto
  r<int>::reallocData(const int,const int,QArrayData::AllocationOptions)'
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(416): note: see reference to function template instantiation 'void QVec
  tor<int>::reallocData(const int,const int,QArrayData::AllocationOptions)' being compiled
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /ERR
  ORREPORT:QUEUE /OUT:"C:\Users\pgroarke\code\experiments\qt_conan\build\Debug\qt_test_tests.exe" /INCREMENTAL /NOLOGO
  /LIBPATH:C:/Users/pgroarke/code/experiments/qt_conan/build/lib /LIBPATH:C:/Users/pgroarke/code/experiments/qt_conan/b
  uild/lib/Debug C:\Users\pgroarke\.conan\data\gtest\1.8.0\bincrafters\stable\package\f6b9d4145acda2f4ee1d45f23527c7e69
  4ee420b\lib\gmock_main.lib C:\Users\pgroarke\.conan\data\gtest\1.8.0\bincrafters\stable\package\f6b9d4145acda2f4ee1d4
  5f23527c7e694ee420b\lib\gmock.lib C:\Users\pgroarke\.conan\data\gtest\1.8.0\bincrafters\stable\package\f6b9d4145acda2
  f4ee1d45f23527c7e694ee420b\lib\gtest.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut3
  2.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed
  /DEBUG /PDB:"C:/Users/pgroarke/code/experiments/qt_conan/build/Debug/qt_test_tests.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /
  DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/pgroarke/code/experiments/qt_conan/build/Debug/qt_test_tests.lib" /MACHINE:X6
  4  /machine:x64 qt_test_tests.dir\Debug\main.obj
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QString::~QString(void)" (_
_imp_??1QString@@QEAA@XZ) referenced in function "public: __cdecl `anonymous namespace'::dx_curves_window::dx_curves_wi
ndow(void)" (??0dx_curves_window@?A0x362f2019@@QEAA@XZ) [C:\Users\pgroarke\code\experiments\qt_conan\build\qt_test_test
s.vcxproj]
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QString::QString(char const
 *)" (__imp_??0QString@@QEAA@PEBD@Z) referenced in function "public: __cdecl `anonymous namespace'::dx_curves_window::d
x_curves_window(void)" (??0dx_curves_window@?A0x362f2019@@QEAA@XZ) [C:\Users\pgroarke\code\experiments\qt_conan\build\q
t_test_tests.vcxproj]
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static void __cdecl QCoreApplicatio
n::processEvents(class QFlags<enum QEventLoop::ProcessEventsFlag>)" (__imp_?processEvents@QCoreApplication@@SAXV?$QFlag
s@W4ProcessEventsFlag@QEventLoop@@@@@Z) referenced in function "public: __cdecl `anonymous namespace'::dx_curves_window
::dx_curves_window(void)" (??0dx_curves_window@?A0x362f2019@@QEAA@XZ) [C:\Users\pgroarke\code\experiments\qt_conan\buil
d\qt_test_tests.vcxproj]
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl QWidget::setWindowTitl
e(class QString const &)" (__imp_?setWindowTitle@QWidget@@QEAAXAEBVQString@@@Z) referenced in function "public: __cdecl
 `anonymous namespace'::dx_curves_window::dx_curves_window(void)" (??0dx_curves_window@?A0x362f2019@@QEAA@XZ) [C:\Users
\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj]
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QDialog::QDialog(class QWid
get *,class QFlags<enum Qt::WindowType>)" (__imp_??0QDialog@@QEAA@PEAVQWidget@@V?$QFlags@W4WindowType@Qt@@@@@Z) referen
ced in function "public: __cdecl `anonymous namespace'::dx_curves_window::dx_curves_window(void)" (??0dx_curves_window@
?A0x362f2019@@QEAA@XZ) [C:\Users\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj]
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl QDialog::~QDialog(v
oid)" (__imp_??1QDialog@@UEAA@XZ) referenced in function "int `public: __cdecl `anonymous namespace'::dx_curves_window:
:dx_curves_window(void)'::`1'::dtor$1" (?dtor$1@?0???0dx_curves_window@?A0x362f2019@@QEAA@XZ@4HA) [C:\Users\pgroarke\co
de\experiments\qt_conan\build\qt_test_tests.vcxproj]
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QApplication::QApplication(
int &,char * *,int)" (__imp_??0QApplication@@QEAA@AEAHPEAPEADH@Z) referenced in function "public: __cdecl `anonymous na
mespace'::dx_curves_window::dx_curves_window(void)" (??0dx_curves_window@?A0x362f2019@@QEAA@XZ) [C:\Users\pgroarke\code
\experiments\qt_conan\build\qt_test_tests.vcxproj]
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl QApplication::~QApp
lication(void)" (__imp_??1QApplication@@UEAA@XZ) referenced in function "int `public: __cdecl `anonymous namespace'::dx
_curves_window::dx_curves_window(void)'::`1'::dtor$0" (?dtor$0@?0???0dx_curves_window@?A0x362f2019@@QEAA@XZ@4HA) [C:\Us
ers\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj]
C:\Users\pgroarke\code\experiments\qt_conan\build\Debug\qt_test_tests.exe : fatal error LNK1120: 8 unresolved externals
 [C:\Users\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj]
Done Building Project "C:\Users\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj" (default targets) -- FA
ILED.

Done Building Project "C:\Users\pgroarke\code\experiments\qt_conan\build\ALL_BUILD.vcxproj" (default targets) -- FAILED
.


Build FAILED.

"C:\Users\pgroarke\code\experiments\qt_conan\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj" (default target) (3) ->
(ClCompile target) ->
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(327): warning C4127: conditional expression is constant [C:\Users\pgroa
rke\code\experiments\qt_conan\build\qt_test_tests.vcxproj]
  c:\.conan\20e7x7t5\1\include\qtcore\qvector.h(311): warning C4127: conditional expression is constant [C:\Users\pgroa
rke\code\experiments\qt_conan\build\qt_test_tests.vcxproj]


"C:\Users\pgroarke\code\experiments\qt_conan\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj" (default target) (3) ->
(Link target) ->
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QString::~QString(void)"
(__imp_??1QString@@QEAA@XZ) referenced in function "public: __cdecl `anonymous namespace'::dx_curves_window::dx_curves_
window(void)" (??0dx_curves_window@?A0x362f2019@@QEAA@XZ) [C:\Users\pgroarke\code\experiments\qt_conan\build\qt_test_te
sts.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QString::QString(char con
st *)" (__imp_??0QString@@QEAA@PEBD@Z) referenced in function "public: __cdecl `anonymous namespace'::dx_curves_window:
:dx_curves_window(void)" (??0dx_curves_window@?A0x362f2019@@QEAA@XZ) [C:\Users\pgroarke\code\experiments\qt_conan\build
\qt_test_tests.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static void __cdecl QCoreApplicat
ion::processEvents(class QFlags<enum QEventLoop::ProcessEventsFlag>)" (__imp_?processEvents@QCoreApplication@@SAXV?$QFl
ags@W4ProcessEventsFlag@QEventLoop@@@@@Z) referenced in function "public: __cdecl `anonymous namespace'::dx_curves_wind
ow::dx_curves_window(void)" (??0dx_curves_window@?A0x362f2019@@QEAA@XZ) [C:\Users\pgroarke\code\experiments\qt_conan\bu
ild\qt_test_tests.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl QWidget::setWindowTi
tle(class QString const &)" (__imp_?setWindowTitle@QWidget@@QEAAXAEBVQString@@@Z) referenced in function "public: __cde
cl `anonymous namespace'::dx_curves_window::dx_curves_window(void)" (??0dx_curves_window@?A0x362f2019@@QEAA@XZ) [C:\Use
rs\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QDialog::QDialog(class QW
idget *,class QFlags<enum Qt::WindowType>)" (__imp_??0QDialog@@QEAA@PEAVQWidget@@V?$QFlags@W4WindowType@Qt@@@@@Z) refer
enced in function "public: __cdecl `anonymous namespace'::dx_curves_window::dx_curves_window(void)" (??0dx_curves_windo
w@?A0x362f2019@@QEAA@XZ) [C:\Users\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl QDialog::~QDialog
(void)" (__imp_??1QDialog@@UEAA@XZ) referenced in function "int `public: __cdecl `anonymous namespace'::dx_curves_windo
w::dx_curves_window(void)'::`1'::dtor$1" (?dtor$1@?0???0dx_curves_window@?A0x362f2019@@QEAA@XZ@4HA) [C:\Users\pgroarke\
code\experiments\qt_conan\build\qt_test_tests.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QApplication::QApplicatio
n(int &,char * *,int)" (__imp_??0QApplication@@QEAA@AEAHPEAPEADH@Z) referenced in function "public: __cdecl `anonymous
namespace'::dx_curves_window::dx_curves_window(void)" (??0dx_curves_window@?A0x362f2019@@QEAA@XZ) [C:\Users\pgroarke\co
de\experiments\qt_conan\build\qt_test_tests.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl QApplication::~QA
pplication(void)" (__imp_??1QApplication@@UEAA@XZ) referenced in function "int `public: __cdecl `anonymous namespace'::
dx_curves_window::dx_curves_window(void)'::`1'::dtor$0" (?dtor$0@?0???0dx_curves_window@?A0x362f2019@@QEAA@XZ@4HA) [C:\
Users\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj]
  C:\Users\pgroarke\code\experiments\qt_conan\build\Debug\qt_test_tests.exe : fatal error LNK1120: 8 unresolved externa
ls [C:\Users\pgroarke\code\experiments\qt_conan\build\qt_test_tests.vcxproj]

    2 Warning(s)
    9 Error(s)
```

**Comment by lucienboillod** [comment] 2018-07-04 12:58
Hello,

Sorry for the late reply I was really busy, so I worked a bit on it. 

I found the cause of this link error, the problem is that we do not export the lib variable through CONAN_LIBS, because Qt has a tons of lib, modules differents options (for example only for Qtbase, there is 22 libs to link) etc ... so we cannot use conan variables, which is, I know a big pain .. we are thinking about a different way to do it. 

For now you can resolve the linking error by precising the target to link against, here your minimal example fixed.

[qt-minimal-example.zip](https://github.com/bincrafters/community/files/2163276/qt-minimal-example.zip)

**Comment by p-groarke** [comment] 2018-07-04 20:41
Looking forward to the fix. Ty.

**Comment by madebr** [comment] 2018-08-29 15:34
After #403, I've bumped into this issue as well.

**Comment by ericLemanissier** [comment] 2018-09-25 18:56
Indeed, cmake_multi cannot work with Qt, because cmake_multi it is incompatible with find_package, and Qt supports cmake only via find_package.
For your CMakeLists, you have to use what is described on [Qt doc](http://doc.qt.io/qt-5/cmake-manual.html):
> find_package(Qt5Core CONFIG REQUIRED)
> target_link_libraries(${PROJECT_NAME} Qt5::Core)

as seen on the [test package](https://github.com/bincrafters/conan-qt/blob/stable/5.11.2/test_package/CMakeLists.txt)

**Comment by ManuelMeraz** [comment] 2019-05-20 02:27
> Hello,
> 
> Sorry for the late reply I was really busy, so I worked a bit on it.
> 
> I found the cause of this link error, the problem is that we do not export the lib variable through CONAN_LIBS, because Qt has a tons of lib, modules differents options (for example only for Qtbase, there is 22 libs to link) etc ... so we cannot use conan variables, which is, I know a big pain .. we are thinking about a different way to do it.
> 
> For now you can resolve the linking error by precising the target to link against; follow the Qt documentation: http://doc.qt.io/qt-5/cmake-manual.html
> 
> Here your minimal example fixed.
> [qt-minimal-example.zip](https://github.com/bincrafters/community/files/2163276/qt-minimal-example.zip)

Can we please add this to the README.md for Qt? This seriously took me forever to find. 

An alias called `CONAN_PKG::Qt` gets created which does not point to the libraries. I had to look into the conanbuildinfo.cmake definitions to see that nothing with Qt libraries was inserted in there.

**Comment by ericLemanissier** [comment] 2020-11-09 08:01
This one should finally be solved. Could someone test it in a real-world scneario before we close this issue ?
Please keep in mind that if you are not using qmake, nor qt's cmake modules, you will have to invoke qt tools (moc, uic, rcc etc) manually in your build process: https://github.com/bincrafters/conan-qt/commit/dfd6c07a67601277cf680d4aa6b210f12df3d697#diff-562313e797b8edefb3a9ab1a365280569b92de21a86eb0798fca35d355ee59f7R99

**Comment by IceflowRE** [comment] 2020-11-09 17:37
I can test tomorrow, i use pure cmake and run manually uic, i can test this at least.

**Comment by ericLemanissier** [comment] 2020-11-09 17:44
thanks ! This is not yet on the stable channel, so you have to manually clone the branch `testing/5.15.1` of the [repository](https://github.com/bincrafters/conan-qt/) and export the recipe from the local clone.

**Comment by ShamanTcler** [comment] 2020-11-09 17:55
Is this fix only for Qt 5.15? or does it go back to 5.9 and 5.6? (Previous LTR versions)

**Comment by ericLemanissier** [comment] 2020-11-09 18:07
as said above, currently it's only on the testing/5.15.1 branch. I can cherry-pick the change to other branches too if you need it (but I'm not sure all of these can still be built)

**Comment by IceflowRE** [comment] 2020-11-10 12:39
In my case it seems to work.

**Comment by ericLemanissier** [comment] 2020-11-10 17:51
fixed with https://github.com/bincrafters/conan-qt/pull/61

**Closed by ericLemanissier** 2020-11-10 17:51 UTC
Labels: enhancement
