### ISSUE TITLE
qt/5.15.1@bincrafters/stable:  use -feature-relocatable for static build

### ISSUE THREAD

**Issue by AndreyMlashkin** [bincrafters/community#1278] opened 2020-09-28 11:31 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.1@bincrafters/stable**
  * Operating System+version: **Windows 10**
  * Compiler+version: **any**
  * Conan version: **conan 1.29.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.cppstd=14
build_type=Release
[options]
*:shared=False
*:fPIC=True
*:with_glib=False
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conan install qt/5.15.1@bincrafters/stable -g deploy

every *.prl file contains position dependent paths.
As example, see attachment of qt/lib/libQt5Core.prl

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
QMAKE_PRL_LIBS = -L/Users/andreimalashkin/.conan/data/pcre2/10.33/_/_/package/2d8245d819a6b7543095d62df5d99244060071ba/lib -L/Users/andreimalashkin/.conan/data/double-conversion/3.1.5/_/_/package/2c05b696523a432f7b39159a51219129d095742b/lib -L/Users/andreimalashkin/.conan/data/harfbuzz/2.6.8/_/_/package/42ea0aaac1043ed6a201382559a3b7079d0161ce/lib -L/Users/andreimalashkin/.conan/data/libjpeg/9d/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L/Users/andreimalashkin/.conan/data/sqlite3/3.31.0/_/_/package/0fb5ca7e7eef2dc13e84ceca1633e96c06b88024/lib -L/Users/andreimalashkin/.conan/data/libmysqlclient/8.0.17/_/_/package/02c55d2bdd0704a4468c3954b5ca79fea24fa8ce/lib -L/Users/andreimalashkin/.conan/data/libpq/11.5/_/_/package/6615b55b95ff43a02a83c3955d071acd71dad079/lib -L/Users/andreimalashkin/.conan/data/odbc/2.3.7/_/_/package/5f4c4ed8ddf27bb70b22f93ac66b6827fc5411d1/lib -L/Users/andreimalashkin/.conan/data/zstd/1.4.4/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L/Users/andreimalashkin/.conan/data/openssl/1.1.1g/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L/Users/andreimalashkin/.conan/data/glib/2.65.1/_/_/package/6b69aa859b3130e0da5f4450fd2f86f305364cdc/lib -L/Users/andreimalashkin/.conan/data/freetype/2.10.2/_/_/package/42b58dfbaf06fc41aabbe10ba829e1cc77d0ecd6/lib -L/Users/andreimalashkin/.conan/data/libffi/3.2.1/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L/Users/andreimalashkin/.conan/data/pcre/8.41/_/_/package/064642ce7e7bf70db3db6199426b09127c22d8c2/lib -L/Users/andreimalashkin/.conan/data/libelf/0.8.13/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L/Users/andreimalashkin/.conan/data/libgettext/0.20.1/_/_/package/9560275f20df8f43a7b2d10c89c0de521253a3bb/lib -L/Users/andreimalashkin/.conan/data/libpng/1.6.37/_/_/package/88955cec2844f731470e07bd44ce5a3a24ec88b7/lib -L/Users/andreimalashkin/.conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L/Users/andreimalashkin/.conan/data/bzip2/1.0.8/_/_/package/75fe66fbfe61230e9fcbb361f13b6b3baa483e0a/lib -L/Users/andreimalashkin/.conan/data/libiconv/1.16/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -framework DiskArbitration -framework IOKit -lm -framework AppKit -framework Security -framework ApplicationServices -ldouble-conversion -lpcre2-posix -lpcre2-8 -lpcre2-16 -lpcre2-32 -lzstd -lgthread-2.0 -lgio-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -liconv -lresolv -framework Foundation -framework CoreServices -framework CoreFoundation -lz -lffi -lpcreposix -lpcre -lpcre16 -lpcre32 -lbz2 -lelf -lgnuintl -lcharset QMAKE_PRL_LIBS_FOR_CMAKE = -L/Users/andreimalashkin/.conan/data/pcre2/10.33/_/_/package/2d8245d819a6b7543095d62df5d99244060071ba/lib;-L/Users/andreimalashkin/.conan/data/double-conversion/3.1.5/_/_/package/2c05b696523a432f7b39159a51219129d095742b/lib;-L/Users/andreimalashkin/.conan/data/harfbuzz/2.6.8/_/_/package/42ea0aaac1043ed6a201382559a3b7079d0161ce/lib;-L/Users/andreimalashkin/.conan/data/libjpeg/9d/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib;-L/Users/andreimalashkin/.conan/data/sqlite3/3.31.0/_/_/package/0fb5ca7e7eef2dc13e84ceca1633e96c06b88024/lib;-L/Users/andreimalashkin/.conan/data/libmysqlclient/8.0.17/_/_/package/02c55d2bdd0704a4468c3954b5ca79fea24fa8ce/lib;-L/Users/andreimalashkin/.conan/data/libpq/11.5/_/_/package/6615b55b95ff43a02a83c3955d071acd71dad079/lib;-L/Users/andreimalashkin/.conan/data/odbc/2.3.7/_/_/package/5f4c4ed8ddf27bb70b22f93ac66b6827fc5411d1/lib;-L/Users/andreimalashkin/.conan/data/zstd/1.4.4/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib;-L/Users/andreimalashkin/.conan/data/openssl/1.1.1g/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib;-L/Users/andreimalashkin/.conan/data/glib/2.65.1/_/_/package/6b69aa859b3130e0da5f4450fd2f86f305364cdc/lib;-L/Users/andreimalashkin/.conan/data/freetype/2.10.2/_/_/package/42b58dfbaf06fc41aabbe10ba829e1cc77d0ecd6/lib;-L/Users/andreimalashkin/.conan/data/libffi/3.2.1/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib;-L/Users/andreimalashkin/.conan/data/pcre/8.41/_/_/package/064642ce7e7bf70db3db6199426b09127c22d8c2/lib;-L/Users/andreimalashkin/.conan/data/libelf/0.8.13/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib;-L/Users/andreimalashkin/.conan/data/libgettext/0.20.1/_/_/package/9560275f20df8f43a7b2d10c89c0de521253a3bb/lib;-L/Users/andreimalashkin/.conan/data/libpng/1.6.37/_/_/package/88955cec2844f731470e07bd44ce5a3a24ec88b7/lib;-L/Users/andreimalashkin/.conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib;-L/Users/andreimalashkin/.conan/data/bzip2/1.0.8/_/_/package/75fe66fbfe61230e9fcbb361f13b6b3baa483e0a/lib;-L/Users/andreimalashkin/.conan/data/libiconv/1.16/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib;-framework;DiskArbitration;-framework;IOKit;-lm;-framework;AppKit;-framework;Security;-framework;ApplicationServices;-ldouble-conversion;-lpcre2-posix;-lpcre2-8;-lpcre2-16;-lpcre2-32;-lzstd;-lgthread-2.0;-lgio-2.0;-lgmodule-2.0;-lgobject-2.0;-lglib-2.0;-liconv;-lresolv;-framework;Foundation;-framework;CoreServices;-framework;CoreFoundation;-lz;-lffi;-lpcreposix;-lpcre;-lpcre16;-lpcre32;-lbz2;-lelf;-lgnuintl;-lcharset;;
```

</details>

### Solution
add -feature-relocatable flag to static builds
https://www.qt.io/blog/qt-is-relocatable

**Comment by ericLemanissier** [comment] 2020-09-28 11:37
you can already enable it by using option qt:config="-feature-relocatable".  Does it solve your problem?

**Comment by AndreyMlashkin** [comment] 2020-09-28 13:15
Yes, it works and fixes my problem!
Will you add this option if building qt as static lib?

**Comment by ericLemanissier** [comment] 2020-09-28 13:19
usually in these cases, it is best to follow what the upstream project does. Here, qt never enables this feature automatically, but only when the user asks for it, because it changes the behavior for translation files. So I think it's better to keep it this way (opt-in)

**Comment by AndreyMlashkin** [comment] 2020-09-28 13:23
Most of the projects also does not set fPic=True for static build. This qt compilation option is basically about the same. In order to use qt, you need to compile it locally.

**Comment by Dark-Passenger** [comment] 2020-09-28 19:09
> Yes, it works and fixes my problem!
> Will you add this option if building qt as static lib?

Um how did you make this work exactly ? I too face the same problem of prl files containing absolute paths to third party dependancies and I had tried and failed to fix it using `feature-relocatable`  back in qt 5.14 I thought something might have had changed and tried with qt 5.15.1 but have the same results. I would love to hear how this problem was resolved ? because to me the only solution for static builds seems to either always build on the machine (no prebuilt) which is what we use or after building strip all lib paths from prl files (not something I really have a lot of experience with since I don't know conan that well).

**Comment by AndreyMlashkin** [comment] 2020-09-29 08:12
According to this https://www.qt.io/blog/qt-is-relocatable
the feature was introduced in 5.14.0, so it should work for you as well.

In my conanfile.py, I have the following:

    def requirements(self):
        self.requires.add('qt/5.15.0@bincrafters/stable')
        self.options["qt"].config = '-feature-relocatable'

**Comment by Dark-Passenger** [comment] 2020-09-29 09:30
> According to this https://www.qt.io/blog/qt-is-relocatable
> the feature was introduced in 5.14.0, so it should work for you as well.
> 
> In my conanfile.py, I have the following:
> 
> ```
> def requirements(self):
>     self.requires.add('qt/5.15.0@bincrafters/stable')
>     self.options["qt"].config = '-feature-relocatable'
> ```

could you share your `qt/lib/libQt5Core.prl` file ?

cause I did set the configuration and I have my user path present in my prl files.

**Comment by AndreyMlashkin** [comment] 2020-09-29 11:51
@Dark-Passenger, you are right, there are still absolute paths in there, I have called grep with my user, but there is "ContainerAdministrator" now. So, the problem is still open

**Comment by ericLemanissier** [comment] 2020-09-29 12:02
Is this reported upstream ?

**Comment by AndreyMlashkin** [comment] 2020-09-30 08:57
I assume, this was reported by @Dark-Passenger  yesterday 
https://bugreports.qt.io/browse/QTBUG-87054?jql=text%20~%20%22feature-relocatable%22

**Comment by ericLemanissier** [comment] 2020-09-30 09:00
ok, thanks. Are absolute path present only for 3rd party libraries ? maybe the qt recipe could be modified to pass these as relative path

**Comment by AndreyMlashkin** [comment] 2020-09-30 09:08
From Qt5Gui.prl
**Qt5Core** dependency specified like: $$[QT_INSTALL_LIBS]/Qt5Core.lib
**double-conversion** specified like: 
C:\\Users\\ContainerAdministrator\\.conan\\data\\double-conversion\\3.1.5\\_\\_\\package\\3fb49604f9c2f729b85ba3115852006824e72cab\\lib\\double-conversion.lib

**Comment by Dark-Passenger** [comment] 2020-09-30 09:17
> I assume, this was reported by @Dark-Passenger yesterday
> https://bugreports.qt.io/browse/QTBUG-87054?jql=text%20~%20%22feature-relocatable%22

I did, it was on my todo list but I kept forgetting 😅

**Comment by Dark-Passenger** [comment] 2020-09-30 09:18
> ok, thanks. Are absolute path present only for 3rd party libraries ? maybe the qt recipe could be modified to pass these as relative path

yes it's only for third party libraries, could it be the extra include, lib paths that are passed to configure that are causing this ?

maybe if we set those in the environment they won't be present in the PRL file ?

**Comment by ericLemanissier** [comment] 2020-10-06 12:27
Relative path would actually not fully solve the problem, because you would still have the version of the dependency in the relative path, so it completely prevents the consumer from overriding dependencies downstream.

**Comment by AndreyMlashkin** [comment] 2020-10-06 17:19
It could be just a  lib name and conan will modify a path to contain this dependency

**Comment by ericLemanissier** [comment] 2020-10-07 07:35
The problem is that it's qmake which finds the absolute path to libraries and stores them, the recipe has no way to change this (apart from patching qt, but we don't have such patch yet)

**Comment by mjvankampen** [comment] 2020-12-18 11:32
Would this be fixed with qt 6 which uses cmake?

**Comment by ericLemanissier** [comment] 2020-12-18 11:43
probably

**Comment by ericLemanissier** [comment] 2021-07-15 07:38
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/qt

**Closed by ericLemanissier** 2021-07-15 07:38 UTC
Labels: bug
