### ISSUE TITLE
libcurl: requires system openssl to be installed when building as shared

### ISSUE THREAD

**Issue by chrisguiney** [bincrafters/community#41] opened 2017-12-27 06:45 UTC
## Description
When OpenSSL is installed by conan as a shared library, libcurl fails to `./configure` when being built as a shared library if there is no system openssl installed (of the same version).

This is because the `./configure` script will create a `conftest` program, and link it against openssl.  The link succeds, because conan correctly configures the relevant environment variables to find `libssl.so` and `libcrypto.so`

However, when `./configure` tries to execute `conftest`, it does have any knowledge of where the conan libraries are (`-rpath` is not set at link time, `LD_LIBRARY_PATH` is not defined at run time)

This causes `conftest` to fail, and subsequently `./configure` to fail as well.

### package
libcurl/7.52.1@bincrafters/stable
OpenSSL/1.0.2m@conan/stable

### Expected result
`./configure` succeeds without requiring (the correct version of) OpenSSL to be installed system-wide

### Actual result
`./configure` fails if (the correct version of) OpenSSL is not installed system wide.

### Steps to reproduce
Docker is incredibly helpful for quickly reproducing this:

```docker
FROM debian:latest

RUN apt update -y
RUN apt install -y apt-utils gcc libtool-bin automake autoconf binutils xutils-dev python-pip
RUN pip install conan
RUN conan remote add bincrafters 'https://api.bintray.com/conan/bincrafters/public-conan'
RUN conan install -o "OpenSSL:shared=True" --build="missing" libcurl/7.52.1@bincrafters/stable
```
### Extra information
- Happens with newer libcurl versions as well

#### Output:
```
OpenSSL/1.0.2m@conan/stable: Package installed eee73bb49a625bcbca3b9b107fdfe004f9a776ab
libcurl/7.52.1@bincrafters/stable: Building your package in /root/.conan/data/libcurl/7.52.1/bincrafters/stable/build/e882cc6df8240276d23efa26b4a720522f20f662
libcurl/7.52.1@bincrafters/stable: Configuring sources in /root/.conan/data/libcurl/7.52.1/bincrafters/stable/source


libcurl/7.52.1@bincrafters/stable: Copying sources to build folder
libcurl/7.52.1@bincrafters/stable: Generator cmake created conanbuildinfo.cmake
libcurl/7.52.1@bincrafters/stable: Generator txt created conanbuildinfo.txt
libcurl/7.52.1@bincrafters/stable: Calling build()
WARN: replace_in_file didn't find pattern '  DEBUG_POSTFIX "-d"' in 'libcurl/lib/CMakeLists.txt' file.
libcurl/7.52.1@bincrafters/stable: WARN: cd libcurl &&  ./configure  --without-libidn  --without-librtmp  --without-libmetalink  --without-libpsl  --without-nghttp2 --with-ssl  --without-libssh2 --with-zlib=/root/.conan/data/zlib/1.2.11/conan/stable/package/351053dac39760023a2758a781ec2b142ea75835/lib  --disable-shared --disable-ldap
libcurl/7.52.1@bincrafters/stable: WARN: cd libcurl &&  ./configure  --without-libidn  --without-librtmp  --without-libmetalink  --without-libpsl  --without-nghttp2 --with-ssl  --without-libssh2 --with-zlib=/root/.conan/data/zlib/1.2.11/conan/stable/package/351053dac39760023a2758a781ec2b142ea75835/lib  --disable-shared --disable-ldap
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking whether to enable debug build options... no
checking whether to enable compiler optimizer... (assumed) yes
checking whether to enable strict compiler warnings... no
checking whether to enable compiler warnings as errors... no
checking whether to enable curl debug memory tracking... no
checking whether to enable hiding of library internal symbols... yes
checking whether to enable c-ares for DNS lookups... no
checking whether to disable dependency on -lrt... (assumed no)
checking for path separator... :
checking for sed... /bin/sed
checking for grep... /bin/grep
checking for egrep... /bin/grep -E
checking for ar... /usr/bin/ar
checking for a BSD-compatible install... /usr/bin/install -c
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/root/.conan/data/libcurl/7.52.1/bincrafters/stable/build/e882cc6df8240276d23efa26b4a720522f20f662/libcurl':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
libcurl/7.52.1@bincrafters/stable: 
libcurl/7.52.1@bincrafters/stable: ERROR: Package 'e882cc6df8240276d23efa26b4a720522f20f662' build failed
libcurl/7.52.1@bincrafters/stable: WARN: Build folder /root/.conan/data/libcurl/7.52.1/bincrafters/stable/build/e882cc6df8240276d23efa26b4a720522f20f662
ERROR: libcurl/7.52.1@bincrafters/stable: Error in build() method, line 139
	self.run(configure)
	ConanException: Error 256 while executing cd libcurl &&  ./configure  --without-libidn  --without-librtmp  --without-libmetalink  --without-libpsl  --without-nghttp2 --with-ssl  --without-libssh2 --with-zlib=/root/.conan/data/zlib/1.2.11/conan/stable/package/351053dac39760023a2758a781ec2b142ea75835/lib  --disable-shared --disable-ldap
The command '/bin/sh -c conan install -o "OpenSSL:shared=True" --build="missing" libcurl/7.52.1@bincrafters/stable' returned a non-zero code: 1
```

#### config.log
```configure:4469: checking whether we are cross compiling
configure:4477: gcc -o conftest -m64 -s -I/root/.conan/data/OpenSSL/1.0.2m/conan/stable/package/eee73bb49a625bcbca3b9b107fdfe004f9a776ab/include -I/root/.conan/data/zlib/1.2.11/conan/stable/package/351053dac39760023a2758a781ec2b142ea75835/include -DNDEBUG -m64 -L/root/.conan/data/OpenSSL/1.0.2m/conan/stable/package/eee73bb49a625bcbca3b9b107fdfe004f9a776ab/lib -L/root/.conan/data/zlib/1.2.11/conan/stable/package/351053dac39760023a2758a781ec2b142ea75835/lib conftest.c -lssl -lcrypto -ldl -lz >&5
configure:4481: $? = 0
configure:4488: ./conftest
./conftest: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
configure:4492: $? = 127
configure:4499: error: in `/root/.conan/data/libcurl/7.52.1/bincrafters/stable/build/e882cc6df8240276d23efa26b4a720522f20f662/libcurl':
configure:4501: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

* Conan version: **v0.30.3**
* Operating System: **Linux**
* Compiler+version: **gcc-6.3**
* Docker image: **debian:latest**

**Comment by theirix** [comment] 2017-12-27 06:50
Thank you for reporting. I handled this case with system openssl in a special way in a package because got a similar error once. I'll look into this bug this Friday.

**Comment by chrisguiney** [comment] 2017-12-27 06:53
I see a few possible outcomes for this:

1. the OpenSSL package should always build a static library (this requires cooperation from the OpenSSL package maintainer -- I'm also not sure if gcc will always prefer a static link to a dynamic if both are available)

2. Set `LD_LIBRARY_PATH` during `./configure` - would resolve this particular issue

3. Escalate this to conan proper, to have the autotool helpers automatically set `LD_LIBRARY_PATH` -- I imagine this will be the case with most packages that use autotools

Not sure if the community has encountered this situation much -- so I figured I'd start reporting here

**Comment by theirix** [comment] 2017-12-29 11:32
Fixing upstream autotools is almost impossible. I saw a lot of autoconf scripts that are broken when conftest dependencies require additional libs not in system pathes.

I fixed the issue by adding `RunEnvironment` for configure and make - it is the second way. It is like https://github.com/bincrafters/conan-libevent/blob/stable/2.1.8/conanfile.py#L54 but more accurate and standardized. Added in testing/7.52.1, will be in stable/7.52.1 soon.

Will close this ticket after discussion

**Comment by ForNeVeR** [comment] 2018-01-02 10:50
I am sorry if I misinterpret curl versioning scheme in some way, but shouldn't it be fixed in 7.56.1, too? Looks like 7.56.1 is still broken at the moment (and 7.52.1 is, indeed, fixed).

**Comment by theirix** [comment] 2018-01-03 08:28
@ForNeVeR 7.52.1 works fine both for stable and testing. Please try running the test in Docker - "Steps to reproduce" from OP. Just checked, runs fine.

Bugfix will be ported to 7.56.1, 7.50.1 and other stable versions soon. I'll need to update READMEs and compatibility with conan 1.0

**Comment by theirix** [comment] 2018-01-04 11:14
@ForNeVeR could you please check the issue mentioned at https://github.com/lasote/conan-libcurl/issues/12#issuecomment-354740289 with bincrafters' stable/7.52.1? Does it work now by default or it's still needed to add `target_link_libraries` in your app?

**Comment by ForNeVeR** [comment] 2018-01-04 12:04
@theirix cleaned my `~/.conan/data` and tried right now. With 7.52.1, it's still required to add the following:
```cmake
target_link_libraries(xxx crypt32 ws2_32)
```

With 7.56.1, `crypt32` is no longer necessary, and it links with just `ws2_32` added.

If that matters, I'm using VS2017 and compiling for x64.

I don't know much neither about how Conan+CMake work nor about libcurl linkage (I'm just a modest libcurl user and a Conan beginner). Is this requirement to add `target_link_libraries` unusual?

**Comment by theirix** [comment] 2018-01-04 17:26
@ForNeVeR I have updated 7.52.1 with the required dependencies. Could you please clean and check again?

**Comment by ForNeVeR** [comment] 2018-01-05 03:55
Unfortunately, nothing has changed. I've also found that [the latest published package on bintray](https://bintray.com/bincrafters/public-conan/libcurl%3Abincrafters/7.52.1%3Astable) is marked as published on 2017-12-29, so I've made sure to use the version from git:

```console
$ git clone git@github.com:bincrafters/conan-libcurl.git
$ cd .\conan-libcurl\
$ conan export libcurl/7.52.1@bincrafters/stable
$ [and now build my project]
```

And even after that it required me to link with both `ws2_32` and `crypt32`.

Maybe something's wrong with my actions? My `CMakeLists.txt` looks basically like this:

```cmake
cmake_minimum_required(VERSION 2.8)

project("appname")

if (EXISTS ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    conan_basic_setup()
endif()

add_executable(appname
    file.cpp
)

target_link_libraries(appname
    libcurl
)

if (WIN32)
    target_link_libraries(appname
        crypt32
        ws2_32
    )
endif()
```

Could it cause the issue somehow?

**Comment by theirix** [comment] 2018-01-05 09:51
I think you have missed `
target_link_libraries(timer ${CONAN_LIBS})`.
See example at https://conanio.readthedocs.io/en/latest/getting_started.html

**Comment by ForNeVeR** [comment] 2018-01-05 10:53
Ah, thank you! I've been able to compile my code without any additional libs.

**Comment by theirix** [comment] 2018-01-05 15:47
Great, glad to help. Closing the ticket because 7.52.1 works fine. Changes will be backported to other versions after CI load decreases.

**Closed by theirix** 2018-01-05 15:47 UTC
