### ISSUE TITLE
GTest 1.8 :Link error with error LNK2019: unresolved external symbol __std_reverse_trivially_swappable_4

### ISSUE THREAD

**Issue by ShamanTcler** [bincrafters/community#333] opened 2018-06-25 17:02 UTC
Same issue reported here: https://github.com/lasote/conan-gtest/issues/41
Replicated here as this is the "newer" process :)

Win 10
Conan 1.4.5
MSVS 2015 compiler
Ninja build

I admit I am new to Conan so likely a user error, but here goes.

prompt>conan search
test/1.8.0@bincrafters/stable

Conanfile.txt:
[conanfile.txt](https://github.com/bincrafters/community/files/2133989/conanfile.txt)

Cmakelists.txt:
[CMakeLists.txt](https://github.com/bincrafters/community/files/2133993/CMakeLists.txt)

This is really a .cpp from your github
[main.txt](https://github.com/bincrafters/community/files/2133994/main.txt)

Do an out of source build:
rm -r build
mkdir build
cd build

conan install .. -s build_type=Debug
conan install .. -s build_type=Release

cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
ninja

cd ..

Resulting log
[log.txt](https://github.com/bincrafters/community/files/2133995/log.txt)

I thought this would be a simple enough example ... what am I missing?

**Comment by uilianries** [comment] 2018-06-26 03:32
I just create the project https://github.com/uilianries/conan-cmake-gtest-error/tree/master to reproduce your scenario;

I didn't see any error on Linux. I need to on Windows to make sure.

**Comment by ShamanTcler** [comment] 2018-06-26 10:53
So I dropped back to version 1.7 ... worked perfectly. Just changed a 8 to 7... viola

I did find these links:

https://github.com/google/googletest/issues/292

and

https://www.leadwerks.com/community/topic/17064-solved-c-compile-error/

**Comment by uilianries** [comment] 2018-06-26 11:31
from slack conversation:

> well, it's possible to put an warning message in the package
when the user runs `conan install gtest/1.8.0@bincrafters/stable`
it could receive the message based on host configuration
msvc + version

We have used `configure(self)` as entrypoint for warning messages many times.

**Comment by uilianries** [comment] 2018-06-26 11:32
Any thought @SSE4 ?

**Comment by ShamanTcler** [comment] 2018-06-26 14:02
issue 335 appears to be on the same/similar topic

**Comment by SSE4** [comment] 2018-06-28 03:49
super weird error, symbol **__std_reverse_trivially_swappable_4** must be something from the standard library, which may indicate some kind of runtime library mismatch or generic compiler flags mismatch.

**Comment by matkam7** [comment] 2018-07-21 03:51
I only get this issue when using the prebuilt static packages (it does works with _--build gtest_). 

One specific example is:
[full_settings]
arch=x86_64
  &nbsp;&nbsp;    build_type=Release
  &nbsp;&nbsp;    compiler=Visual Studio
   &nbsp;&nbsp;   compiler.runtime=MT
    &nbsp;&nbsp;  compiler.version=15
  &nbsp;&nbsp;    os=Windows
[full_options]
 &nbsp;&nbsp;     build_gmock=True
  &nbsp;&nbsp;    shared=False

It might have to do with my application targeting c++17, and if so adding a 'cppstd' is a potential fix.

**Comment by SSE4** [comment] 2018-07-21 08:43
@matkam7  quick question - if you add **cppstd=17** into your profile and rebuild - does it fix an issue? I believe this action should add appropriate flags to the gtest CMake.

**Comment by matkam7** [comment] 2018-07-22 01:56
**cppstd** isn't currently a setting for gtest, and i'm not even sure that its the problem.

**Comment by SSE4** [comment] 2018-08-05 09:40
@ShamanTcler it seems like I was finally able to reproduce your issue, and it appears like settings mismatch.
package hash from your output (**3f7b6d42d6c995a23d193db1f844ed23ae943226**) is for Visual Studio 2017 (you may inspect it at `%USERPROFILE%\.conan\data\gtest\1.8.0\bincrafters\stable\package\3f7b6d42d6c995a23d193db1f844ed23ae943226\conaninfo.txt`):
```
[settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=15
    os=Windows

[requires]


[options]
    build_gmock=True
    shared=False

[full_settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=15
    os=Windows

[full_requires]


[full_options]
    build_gmock=True
    shared=False

[recipe_hash]
    2cd87b773ba223aa816ed2ff97fb89db

[env]

```
however, from your post it seems like you're building for Visual Studio 2015 (which is version 14).
so, either change your default profile like `conan profile update settings.compiler.version=14 default`.
(you may also inspect your default profile by running `conan profile show default`)
or use more specific commands, like:
```
conan install .. -s build_type=Debug -s compiler.version=14
conan install .. -s build_type=Release -s compiler.version=14
```
therefore, correct output should look like:
```
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Current conanbuildinfo.cmake directory: C:/bincrafters/gtest_sandbox/build
-- Conan: Using cmake targets configuration
-- Library gmock_main found C:/Users/SSE4/.conan/data/gtest/1.8.0/bincrafters/stable/package/bd92306c84f896e3336009314c7cb772b0f833e5/lib/gmock_main.lib
-- Library gmock found C:/Users/SSE4/.conan/data/gtest/1.8.0/bincrafters/stable/package/bd92306c84f896e3336009314c7cb772b0f833e5/lib/gmock.lib
-- Library gtest found C:/Users/SSE4/.conan/data/gtest/1.8.0/bincrafters/stable/package/bd92306c84f896e3336009314c7cb772b0f833e5/lib/gtest.lib
-- Library gmock_main found C:/Users/SSE4/.conan/data/gtest/1.8.0/bincrafters/stable/package/1665f9c00f70e0be8293d6c951d72582760d4437/lib/gmock_main.lib
-- Library gmock found C:/Users/SSE4/.conan/data/gtest/1.8.0/bincrafters/stable/package/1665f9c00f70e0be8293d6c951d72582760d4437/lib/gmock.lib
-- Library gtest found C:/Users/SSE4/.conan/data/gtest/1.8.0/bincrafters/stable/package/1665f9c00f70e0be8293d6c951d72582760d4437/lib/gtest.lib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/bincrafters/gtest_sandbox/build
[2/2] Linking CXX executable gtest_1.exe
```
with package id **1665f9c00f70e0be8293d6c951d72582760d4437**

**Comment by ShamanTcler** [comment] 2018-08-06 13:03
Ah I have stumbled into the wonderful of MSVS... so here is the scenario that I believe led me to this.  I installed MSVS 2017 pro, then selected the option to "down grade" to MSVS 2015. So I think what you get is the MSVS 2017 IDE environment with the MSVS 2015 compiler.

The reason I say this is I also need Intel FORTRAN 15., and Intel 15.0.7 IS compatible with MSVS 2015. But Intel 15.0.7 would NOT install correctly, it kept reporting no MSVS C compiler found.

So after numerous install/uninstall/reboot combinations ... I went out an found an OLD  MSVS 2015 installer and installed it. Finally a miracle occurred Intel 15.0.7 installed and found MSVS 2015.

So this leads me to believe that "down grading" really means just adding a second compiler to the previous compiler set.  So MSVS 2017 IDE is active even though the compiler being used was MSVS 2015.

It appears to me to be a bit of a "pea shell game" happening (https://en.wikipedia.org/wiki/Shell_game)

So my lesson learned ... don't downgrade, try to use the "original"

**Comment by SSE4** [comment] 2018-08-06 16:14
@ShamanTcler please tell me if we can close an issue now

**Comment by SSE4** [comment] 2018-08-08 13:42
I am closing for now, please open new issue if there are other problems

**Comment by Blubbz0r** [comment] 2018-09-27 15:49
I'm getting the same linker error when trying to use the package on our build server. It works fine on my local machine though. I'm guessing that the Visual Studio version on our build server is the culprit here (15.4.0). My local machine is up-to-date (15.8.5).

Reason: There is pre-built package on conan-center that is downloaded by the build server. Using that package results in the linker error. I manually removed the package and forced to build from source. This resulted in a successful build.

**Comment by uilianries** [comment] 2018-12-18 11:52
@glennguo did you try using gtest 1.8.1 or 1.8.0?

**Comment by glennguo** [comment] 2018-12-18 13:16
@uilianries it was Release 1.8.0

**Comment by Croydon** [comment] 2019-06-04 13:22
Is this still a problem?

**Comment by Croydon** [comment] 2019-09-23 00:02
Closing because of no answer.

Furthermore, gtest is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index). Please migrate to the gtest version there and report potential problems there

**Closed by Croydon** 2019-09-23 00:02 UTC
Labels: bug

**Comment by sfhacker** [comment] 2021-02-16 15:17
This issue is two years old! Wow.
Just built gtest 1.10.0 from source on Windows 10 x64 with no issues at all!

![image](https://user-images.githubusercontent.com/25817529/108082436-33cf6f00-70c6-11eb-9571-da1b11123802.png)

**Comment by erikzenker** [comment] 2021-02-21 14:02
@sfhacker the issue is not about building gtest but usin the conan gtest package!
