### ISSUE TITLE
[boost_package_tools] boost_package_tools can't be retrieved

### ISSUE THREAD

**Issue by Barben360** [bincrafters/community#717] opened 2019-04-04 12:22 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **conan_package_tools/<all-versions>**
  * Operating System+version: **Ubuntu/Windows/MacOSX**
  * Conan version: **conan 1.12.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

Any profile

### Steps to reproduce (Include if Applicable)
boost_package_tools is found in bincrafters when performing search:
```
> conan search boost_package_tools -r bincrafters
Existing package recipes:

boost_package_tools/1.65.1@bincrafters/stable
boost_package_tools/1.65.1@bincrafters/testing
boost_package_tools/1.66.0@bincrafters/stable
boost_package_tools/1.66.0@bincrafters/testing
boost_package_tools/1.67.0@bincrafters/testing
boost_package_tools/1.68.0@bincrafters/testing
```
However it can't be retrieved:

```
> conan download boost_package_tools/1.66.0@bincrafters/stable -r bincrafters
ERROR: 'boost_package_tools/1.66.0@bincrafters/stable' not found in remote 'bincrafters'
```

Same thing with any other version of the package. It seems to have been updated on April 1st, 2019 which is the moment when I noticed the problems started.

Tested on Linux, Windows, MacOSX with different profiles.

**Comment by loosechainsaw** [comment] 2019-04-05 01:55
I am having the exact same issue.

**Comment by loosechainsaw** [comment] 2019-04-05 07:19
Is this going to be fixed. I am using this and it is a total blocker.

**Comment by Barben360** [comment] 2019-04-05 07:37
> Is this going to be fixed. I am using this and it is a total blocker.

While waiting for a fix you can still create the package from the [github repository](https://github.com/bincrafters/conan-boost-package-tools) and run:

```
conan create . bincrafters/stable -b outdated
```

or checkout another branch if you want another version.

Then if you have a personal Conan repository you can upload the generated package on it:

```
conan upload boost_package_tools/1.66.0@bincrafters/stable -r <your-repo> --all
```

and use it from this repo.

**Comment by loosechainsaw** [comment] 2019-04-05 08:05
Thanks

**Comment by uilianries** [comment] 2019-04-05 12:12
This is really weird, the was changed one year ago ... I'll investigate further

**Comment by uilianries** [comment] 2019-04-05 12:21
@loosechainsaw  @Barben360 please, try to download again. I've uploaded the package again. I think it was some inconsistency on Bintray side. The package was there, but something was corrupted.

**Comment by Barben360** [comment] 2019-04-05 12:25
Now I've got:

```
> conan download boost_package_tools/1.66.0@bincrafters/stable -r bincrafters
Downloading conanmanifest.txt
[==================================================] 174B/174B
Downloading conanfile.py
[==================================================] 619B/619B
Downloading conan_export.tgz
[==================================================] 758B/758B
Decompressing conan_export.tgz: 100%|██████████| 758/758 [00:00<00:00, 637kB/s]
boost_package_tools/1.66.0@bincrafters/stable: Getting the complete package list from 'boost_package_tools/1.66.0@bincrafters/stable'...
boost_package_tools/1.66.0@bincrafters/stable: Downloading boost_package_tools/1.66.0@bincrafters/stable:conaninfo.txt
boost_package_tools/1.66.0@bincrafters/stable: Retrieving package conaninfo.txt from remote 'bincrafters'
ERROR: Package binary 'boost_package_tools/1.66.0@bincrafters/stable:conaninfo.txt' not found in 'bincrafters'
```

It goes further but there still seem to be something missing.

**Comment by uilianries** [comment] 2019-04-05 12:29
hmm, it's working for me, please more few minutes, since the server is distributes, it could take some time to replicate all indexes.

```
conan download boost_package_tools/1.66.0@bincrafters/stable -r bincrafters
Downloading conanmanifest.txt
[==================================================] 174B/174B        
Downloading conanfile.py
[==================================================] 619B/619B        
Downloading conan_export.tgz
[==================================================] 758B/758B        
Decompressing conan_export.tgz: 100%|██████████| 758/758 [00:00<00:00, 355kB/s]
Downloading conan_sources.tgz
[==================================================] 1.3KB/1.3KB      
Decompressing conan_sources.tgz: 100%|██████████| 1.30k/1.30k [00:00<00:00, 570kB/s]
boost_package_tools/1.66.0@bincrafters/stable: Getting the complete package list from 'boost_package_tools/1.66.0@bincrafters/stable#bda1805256715afab68cab63fc87e49d'...
boost_package_tools/1.66.0@bincrafters/stable: Downloading boost_package_tools/1.66.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
boost_package_tools/1.66.0@bincrafters/stable: Retrieving package 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 from remote 'bincrafters' 
Downloading conanmanifest.txt
[==================================================] 161B/161B        
Downloading conaninfo.txt
[==================================================] 196B/196B        
Downloading conan_package.tgz
[==================================================] 2.0KB/2.0KB      
Decompressing conan_package.tgz: 100%|██████████| 1.95k/1.95k [00:00<00:00, 1.73MB/s]
boost_package_tools/1.66.0@bincrafters/stable: Package installed 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
```

**Comment by Barben360** [comment] 2019-04-05 12:31
Ok, I'll tell you when it works (still not).

**Comment by uilianries** [comment] 2019-04-05 12:33
Hmm, I can confirm you bug when running with Conan 1.12.3 (outdated). Give me some minutes, but I think it could be a bug from Bintray, since they applied some patches to support Conan 1.14

**Comment by Barben360** [comment] 2019-04-05 12:37
I just upgraded to conan 1.14.1, still the same error.

**Comment by uilianries** [comment] 2019-04-05 13:42
Hi @Barben360 !

Please, enable Conan revisions in you client and try again:

    conan config set general.revisions_enabled=1 
    conan download ...

Also, you can follow the issue https://github.com/conan-io/conan/issues/4906 to keep informed.

**Comment by Barben360** [comment] 2019-04-05 15:22
@uilianries That indeed worked! Thanks a lot.

**Comment by uilianries** [comment] 2019-04-06 23:00
Nice! Closing this issue. Follow https://github.com/conan-io/conan/issues/4906 if you want to keep updated. Regards!

**Closed by uilianries** 2019-04-06 23:00 UTC
Labels: bintray, help wanted
